#!/usr/bin/env node
/* ============================================================================
 *  bench/pixel_cache/nchannel_bench.js — the pixel cache above 4 channels.
 * ----------------------------------------------------------------------------
 *  Released under the MIT License
 *  Copyright (c) 2026 Glenn Wilton, O2 Creative Limited.
 *
 *  WHY A SECOND HARNESS. cache_bench.js is RGB and CMYK, because those were
 *  the only profiles that existed. Both build a CLUT, so a cache MISS there is
 *  one interpolation and the cache is competing against something already
 *  fast. Above 4 input channels KernelND declines the LUT -- an A2B bake is
 *  grid^N cells -- so every pixel walks the full pipeline at ~0.8 MPx/s, and a
 *  miss costs roughly fifty times what it costs in RGB.
 *
 *  Same cache, different economics. That is the point of this file: the
 *  break-even hit rate moves, and content the cache was judged not worth
 *  enabling for in RGB pays here.
 *
 *  Profiles: __tests__/profiles/synthetic_NNch.icc, generated by
 *  `node scripts/make_test_profiles.js`. See docs/deepdive/SyntheticProfiles.md.
 *
 *  Usage:
 *    node bench/pixel_cache/nchannel_bench.js
 *    node bench/pixel_cache/nchannel_bench.js --widths 5,8,12 --slots 4096
 *    node bench/pixel_cache/nchannel_bench.js --px 30000 --iters 5
 * ============================================================================
 */
'use strict';

const fs   = require('fs');
const path = require('path');
const Profile = require('../../src/Profile');
const { Transform, eIntent } = require('../../src/main');

const arg = (name, fallback) => {
    const i = process.argv.indexOf('--' + name);
    return (i !== -1 && process.argv[i + 1] && !process.argv[i + 1].startsWith('--'))
        ? process.argv[i + 1] : fallback;
};

const PX     = parseInt(arg('px', '20000'), 10);
const ITERS  = parseInt(arg('iters', '3'), 10);
const SLOTS  = parseInt(arg('slots', '4096'), 10);
const OUT_CH = parseInt(arg('out', '3'), 10);
const WIDTHS = arg('widths', '4,5,8,12').split(',').map(s => parseInt(s.trim(), 10));
const DIR    = path.join(__dirname, '..', '..', '__tests__', 'profiles');

// ---------------------------------------------------------------------------
//  Content
//
//  TAKE THE HIGH BITS. An LCG's low byte has a short period, so `seed & 0xff`
//  produces content that repeats far more than random -- which reads as a near
//  perfect hit rate on what you believe is unique data. `>>> 16` is what
//  cache_bench.js uses, for the same reason. The distinct-colour count printed
//  in every row is the check: if "noise" is not close to the pixel count, the
//  generator is lying to you.
// ---------------------------------------------------------------------------

function makeNoise(pixelCount, channels){
    const out = new Uint8ClampedArray(pixelCount * channels);
    let seed = 0x13579bdf;
    for(let i = 0; i < out.length; i++){
        seed = (Math.imul(seed, 1103515245) + 12345) | 0;
        out[i] = (seed >>> 16) & 0xFF;
    }
    return out;
}

/** Flat art: `colours` distinct N-channel colours, in runs, no gradients. */
function makeFlat(pixelCount, channels, colours){
    const palette = [];
    for(let c = 0; c < colours; c++){
        const colour = new Array(channels);
        for(let ch = 0; ch < channels; ch++){
            colour[ch] = (Math.imul(c + 1, 2654435761 + ch * 40503) >>> 24) & 0xFF;
        }
        palette.push(colour);
    }
    const out = new Uint8ClampedArray(pixelCount * channels);
    const runLength = 8;
    for(let p = 0; p < pixelCount; p++){
        const colour = palette[Math.floor(p / runLength) % colours];
        for(let ch = 0; ch < channels; ch++) out[p * channels + ch] = colour[ch];
    }
    return out;
}

function distinctColours(buf, channels, pixelCount){
    const seen = new Set();
    for(let p = 0; p < pixelCount; p++){
        let key = '';
        for(let ch = 0; ch < channels; ch++) key += buf[p * channels + ch] + ',';
        seen.add(key);
        if(seen.size > 100000) return '>100k';
    }
    return seen.size;
}

// ---------------------------------------------------------------------------

function loadProfile(n){
    const file = path.join(DIR, 'synthetic_' + String(n).padStart(2, '0') + 'ch.icc');
    if(!fs.existsSync(file)){
        console.error('  missing ' + path.basename(file)
            + ' — run: node scripts/make_test_profiles.js');
        process.exit(1);
    }
    const p = new Profile();
    p.loadBinary(new Uint8Array(fs.readFileSync(file)));
    return p;
}

/**
 * ONE COLD CACHE PER TIMED PASS, and that is not fussiness.
 *
 * The obvious harness builds one Transform and runs the same buffer through
 * it N times. Pass 2 then finds pass 1's entries already resident, so the
 * cache is measured against an image it has already seen -- which no real
 * workload does, and which quietly turns "unique content" into "content with
 * a 4096-entry head start". Taking the best of those passes picks the most
 * warmed one. It reads as several tens of percent of reuse that the data does
 * not contain.
 *
 * A fresh Transform per pass costs a create() each time, which is outside the
 * timed region and negligible against a per-pixel pipeline walk. The stats
 * then describe a single pass over the buffer, which is the question.
 */
function measure(inProfile, outProfile, input, slots){
    let best = 0, stats = { enabled: false, hitRate: 0 };

    for(let i = 0; i < ITERS; i++){
        // pixelCache: true is ONE slot, not "on with a sensible default".
        // Always pass a count -- a single-entry cache on eight distinct
        // colours reads 13%, which looks like a broken cache rather than the
        // mode that was actually asked for.
        //
        // buildLut is off because KernelND declines it above 4 channels
        // anyway; asking would only print the notice once per pass.
        // Warm the JIT on a THROWAWAY transform, not on the one being timed:
        // a warm-up pass over the same buffer would seed the cache with the
        // colours about to be looked up. The pipeline stages are prototype
        // methods, so warming any transform of this shape warms the code.
        const warm = new Transform({ dataFormat: 'int8', buildLut: false, pixelCache: 0 });
        warm.create(inProfile, outProfile, eIntent.relative);
        warm.array(input, false, false, false, Math.min(1000, PX));

        const t = new Transform({ dataFormat: 'int8', buildLut: false, pixelCache: slots });
        t.create(inProfile, outProfile, eIntent.relative);

        const start = process.hrtime.bigint();
        t.array(input, false, false, false, PX);
        const ms = Number(process.hrtime.bigint() - start) / 1e6;

        const mpx = (PX / 1e6) / (ms / 1000);
        if(mpx > best){
            best = mpx;
            stats = t.getPixelCacheStats ? t.getPixelCacheStats()
                                         : { enabled: false, hitRate: 0 };
        }
    }
    return { mpx: best, stats: stats };
}

// ---------------------------------------------------------------------------

console.log('');
console.log('Pixel cache above 4 channels — ' + PX + ' px, ' + ITERS + ' iters, '
    + SLOTS + ' slots, int8, N -> ' + OUT_CH + 'ch');
console.log('');

const outProfile = loadProfile(OUT_CH);

for(const n of WIDTHS){
    const inProfile = loadProfile(n);
    const content = [
        ['noise',             makeNoise(PX, n)],
        ['flat, 256 colours', makeFlat(PX, n, 256)],
        ['flat, 16 colours',  makeFlat(PX, n, 16)],
    ];

    console.log('  ' + n + '-channel input');
    console.log('  ' + '-'.repeat(64));
    console.log('  '
        + 'content'.padEnd(19) + 'distinct'.padStart(9)
        + 'off'.padStart(8) + 'on'.padStart(9)
        + 'gain'.padStart(9) + 'hit%'.padStart(7));

    const row = {};
    for(const pair of content){
        const name = pair[0], input = pair[1];
        const off = measure(inProfile, outProfile, input, 0);
        const on  = measure(inProfile, outProfile, input, SLOTS);
        row[name] = { off: off.mpx, on: on.mpx };
        const declined = on.stats.enabled ? '' : '  (cache declined)';
        console.log('  '
            + name.padEnd(19)
            + String(distinctColours(input, n, PX)).padStart(9)
            + off.mpx.toFixed(2).padStart(8)
            + on.mpx.toFixed(2).padStart(9)
            + ((on.mpx / off.mpx).toFixed(2) + 'x').padStart(9)
            + (Math.round(on.stats.hitRate * 100) + '%').padStart(7)
            + declined);
    }

    // BREAK-EVEN HIT RATE — the number that decides whether to enable it, and
    // the only one here that transfers to content this bench does not have.
    //
    // The noise rows give both ends of a miss: `off` is a miss without a cache,
    // `on` is a miss that also paid for a lookup and a store. The flat-16 `on`
    // row is a hit. Solve for the hit rate at which they cancel:
    //
    //     h.tHit + (1-h).tMiss = tOff
    const tOff  = 1 / row['noise'].off;
    const tMiss = 1 / row['noise'].on;
    const tHit  = 1 / row['flat, 16 colours'].on;
    const breakEven = (tMiss - tOff) / (tMiss - tHit);
    console.log('  ' + '-'.repeat(64));
    console.log('  break-even hit rate: ' + (breakEven * 100).toFixed(1) + '%'
        + '   (miss tax ' + (((tMiss / tOff) - 1) * 100).toFixed(0) + '%'
        + ', hit is ' + (tOff / tHit).toFixed(0) + 'x cheaper than the maths)');
    console.log('');
}

console.log('  Read the noise row. A cache that pays only on flat art is the RGB');
console.log('  result; a cache that pays on noise is the regime change. See');
console.log('  docs/deepdive/PixelCache.md.');
console.log('');
