/*************************************************************************
 *  @license
 *
 *  Copyright © 2019, 2026 Glenn Wilton
 *  O2 Creative Limited
 *************************************************************************/

// ============================================================================
// tetra5d_nch.wasm.js — AUTO-GENERATED from tetra5d_nch.wat
// ============================================================================
//
// Do not edit by hand. Regenerate with:
//   node scripts/gen_tetra56_nch.js && node scripts/compile_kernel_wat.js src/kernels/5d/tetra5d_nch.wat
//
// Exports: interp_tetra5d_nCh (verbatim) + interp_tetra5d_nCh_cached (single-entry).
// Source:  src/kernels/5d/tetra5d_nch.wat
// Size:    4337 bytes .wasm
// ============================================================================

'use strict';

const BASE64 = 'AGFzbQEAAAABJgJgC39/f39/f39/f39/AX9gE39/f39/f39/f39/f39/f39/f38AAwQDAAEBBQMBAAEHOwMGbWVtb3J5AgASaW50ZXJwX3RldHJhNWRfbkNoAAEZaW50ZXJwX3RldHJhNWRfbkNoX2NhY2hlZAACCvYgA74BAQJ/IAJFIANxBEAgCCABQQJ0aiAANgIAIAoPCyACBEAgCCABQQJ0aigCACELIAsgACALayAGbEGAAWpBCHVqIQALIARFIAVxBEAgCCAJIAFqQQJ0aiAANgIAIAoPCyAEBEAgCCAJIAFqQQJ0aigCACELIAtBCHQgACALayAHbGpBgIAgakEUdSEMBSAAQYAQakEMdSEMC0EAIAwgDEEASBshDEH/ASAMIAxBgAJOGyEMIAogDDoAACAKQQFqC50PAS5/IAAhFCABIRUCQANAIBMgA04NASAULQAAIRYgFEEBai0AACEXIBRBAmotAAAhGCAUQQNqLQAAIRkgFEEEai0AACEaIBRBBWohFCAWIAlsIRsgFyAJbCEcIBggCWwhHSAZIAlsIR4gGiAJbCEfIBdB/wFGBEAgDSEmQQAhLwUgHEEQdiAIbCEmIBxBCHZB/wFxIS8LIC9BAEchNiAYQf8BRgRAIAohICAKISFBACEsBSAdQRB2IAdsISAgICAHaiEhIB1BCHZB/wFxISwLIBlB/wFGBEAgCyEiIAshI0EAIS0FIB5BEHYgBmwhIiAiIAZqISMgHkEIdkH/AXEhLQsgGkH/AUYEQCAMISQgDCElQQAhLgUgH0EQdiAFbCEkICQgBWohJSAfQQh2Qf8BcSEuCyAWQf8BRgRAIA8hKEEAISkFIBtBEHYgDmwhKCAbQQh2Qf8BcSEpCyApQQBHISsgJiEnICYgKGohJkEAISpBACE1IDYhNwJAA0ACQANAICAgImogJGogJmohMCAsIC1OIC0gLk5xBEAgISAiaiAkaiAmaiExICEgI2ogJGogJmohMiAhICNqICVqICZqITRBACE4A0AgAiAxQQF0ai8BACE5IDFBAWohMSACIDJBAXRqLwEAITogMkEBaiEyIAIgMEEBdGovAQAhOyAwQQFqITAgAiA0QQF0ai8BACE8IDRBAWohNCA5IDtrICxsIDogOWsgLWxqIDwgOmsgLmxqIT0gO0EEdCA9QQhqQQR1aiE+ID4gOCA1IDYgKiArIC8gKSAQIAQgFRAAIRUgOEEBaiI4IARIDQALBSAsIC5OIC4gLU5xBEAgISAiaiAkaiAmaiExICEgI2ogJWogJmohMiAhICJqICVqICZqITNBACE4A0AgAiAzQQF0ai8BACE5IDNBAWohMyACIDFBAXRqLwEAITogMUEBaiExIAIgMEEBdGovAQAhOyAwQQFqITAgAiAyQQF0ai8BACE8IDJBAWohMiA6IDtrICxsIDwgOWsgLWxqIDkgOmsgLmxqIT0gO0EEdCA9QQhqQQR1aiE+ID4gOCA1IDYgKiArIC8gKSAQIAQgFRAAIRUgOEEBaiI4IARIDQALBSAsIC1OIC4gLE5xBEAgISAiaiAlaiAmaiExICAgImogJWogJmohMiAhICNqICVqICZqITNBACE4A0AgAiAxQQF0ai8BACE5IDFBAWohMSACIDJBAXRqLwEAITogMkEBaiEyIAIgMEEBdGovAQAhOyAwQQFqITAgAiAzQQF0ai8BACE8IDNBAWohMyA5IDprICxsIDwgOWsgLWxqIDogO2sgLmxqIT0gO0EEdCA9QQhqQQR1aiE+ID4gOCA1IDYgKiArIC8gKSAQIAQgFRAAIRUgOEEBaiI4IARIDQALBSAtICxOICwgLk5xBEAgISAjaiAkaiAmaiExICAgI2ogJGogJmohMiAhICNqICVqICZqITRBACE4A0AgAiAyQQF0ai8BACE5IDJBAWohMiACIDFBAXRqLwEAITogMUEBaiExIAIgMEEBdGovAQAhOyAwQQFqITAgAiA0QQF0ai8BACE8IDRBAWohNCA6IDlrICxsIDkgO2sgLWxqIDwgOmsgLmxqIT0gO0EEdCA9QQhqQQR1aiE+ID4gOCA1IDYgKiArIC8gKSAQIAQgFRAAIRUgOEEBaiI4IARIDQALBSAtIC5OIC4gLE5xBEAgISAjaiAlaiAmaiExICAgI2ogJWogJmohMiAgICNqICRqICZqITNBACE4A0AgAiAyQQF0ai8BACE5IDJBAWohMiACIDNBAXRqLwEAITogM0EBaiEzIAIgMEEBdGovAQAhOyAwQQFqITAgAiAxQQF0ai8BACE8IDFBAWohMSA8IDlrICxsIDogO2sgLWxqIDkgOmsgLmxqIT0gO0EEdCA9QQhqQQR1aiE+ID4gOCA1IDYgKiArIC8gKSAQIAQgFRAAIRUgOEEBaiI4IARIDQALBSAuIC1OIC0gLE5xBEAgISAjaiAlaiAmaiExICAgI2ogJWogJmohMiAgICJqICVqICZqITRBACE4A0AgAiAyQQF0ai8BACE5IDJBAWohMiACIDRBAXRqLwEAITogNEEBaiE0IAIgMEEBdGovAQAhOyAwQQFqITAgAiAxQQF0ai8BACE8IDFBAWohMSA8IDlrICxsIDkgOmsgLWxqIDogO2sgLmxqIT0gO0EEdCA9QQhqQQR1aiE+ID4gOCA1IDYgKiArIC8gKSAQIAQgFRAAIRUgOEEBaiI4IARIDQALBUEAITgDQCACIDBBAXRqLwEAITsgMEEBaiEwIDtBBHQhPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwsLCwsLCyA1RSA2cQRAICYgCGohJkEBITVBAiE3DAELDAELCyAqRSArcQRAICcgKGogDmohJkEAITUgNiE3QQEhKgwBCwwBCwsgEkECRgRAIBUgFC0AADoAACAVQQFqIRUgFEEBaiEUBSASQQFGBEAgFUH/AToAACAVQQFqIRULIBQgEWohFAsgE0EBaiETDAALCwuUEAE2fyAAIRQgASEVQQAhRSAEIUYCQANAIBMgA04NASAULQAAIRYgFEEBai0AACEXIBRBAmotAAAhGCAUQQNqLQAAIRkgFEEEai0AACEaIBRBBWohFCAWIBdBCHRyIBhBEHRyIBlBGHRyIUEgGiFCAkAgRSBBIENGIEIgREZxcQRAQQAhRwNAIBUgR2ogSCBHai0AADoAACBHQQFqIUcgRyBGSQ0ACyAVIEZqIRUMAQsgFiAJbCEbIBcgCWwhHCAYIAlsIR0gGSAJbCEeIBogCWwhHyAXQf8BRgRAIA0hJkEAIS8FIBxBEHYgCGwhJiAcQQh2Qf8BcSEvCyAvQQBHITYgGEH/AUYEQCAKISAgCiEhQQAhLAUgHUEQdiAHbCEgICAgB2ohISAdQQh2Qf8BcSEsCyAZQf8BRgRAIAshIiALISNBACEtBSAeQRB2IAZsISIgIiAGaiEjIB5BCHZB/wFxIS0LIBpB/wFGBEAgDCEkIAwhJUEAIS4FIB9BEHYgBWwhJCAkIAVqISUgH0EIdkH/AXEhLgsgFkH/AUYEQCAPIShBACEpBSAbQRB2IA5sISggG0EIdkH/AXEhKQsgKUEARyErICYhJyAmIChqISZBACEqQQAhNSA2ITcCQANAAkADQCAgICJqICRqICZqITAgLCAtTiAtIC5OcQRAICEgImogJGogJmohMSAhICNqICRqICZqITIgISAjaiAlaiAmaiE0QQAhOANAIAIgMUEBdGovAQAhOSAxQQFqITEgAiAyQQF0ai8BACE6IDJBAWohMiACIDBBAXRqLwEAITsgMEEBaiEwIAIgNEEBdGovAQAhPCA0QQFqITQgOSA7ayAsbCA6IDlrIC1saiA8IDprIC5saiE9IDtBBHQgPUEIakEEdWohPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwUgLCAuTiAuIC1OcQRAICEgImogJGogJmohMSAhICNqICVqICZqITIgISAiaiAlaiAmaiEzQQAhOANAIAIgM0EBdGovAQAhOSAzQQFqITMgAiAxQQF0ai8BACE6IDFBAWohMSACIDBBAXRqLwEAITsgMEEBaiEwIAIgMkEBdGovAQAhPCAyQQFqITIgOiA7ayAsbCA8IDlrIC1saiA5IDprIC5saiE9IDtBBHQgPUEIakEEdWohPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwUgLCAtTiAuICxOcQRAICEgImogJWogJmohMSAgICJqICVqICZqITIgISAjaiAlaiAmaiEzQQAhOANAIAIgMUEBdGovAQAhOSAxQQFqITEgAiAyQQF0ai8BACE6IDJBAWohMiACIDBBAXRqLwEAITsgMEEBaiEwIAIgM0EBdGovAQAhPCAzQQFqITMgOSA6ayAsbCA8IDlrIC1saiA6IDtrIC5saiE9IDtBBHQgPUEIakEEdWohPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwUgLSAsTiAsIC5OcQRAICEgI2ogJGogJmohMSAgICNqICRqICZqITIgISAjaiAlaiAmaiE0QQAhOANAIAIgMkEBdGovAQAhOSAyQQFqITIgAiAxQQF0ai8BACE6IDFBAWohMSACIDBBAXRqLwEAITsgMEEBaiEwIAIgNEEBdGovAQAhPCA0QQFqITQgOiA5ayAsbCA5IDtrIC1saiA8IDprIC5saiE9IDtBBHQgPUEIakEEdWohPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwUgLSAuTiAuICxOcQRAICEgI2ogJWogJmohMSAgICNqICVqICZqITIgICAjaiAkaiAmaiEzQQAhOANAIAIgMkEBdGovAQAhOSAyQQFqITIgAiAzQQF0ai8BACE6IDNBAWohMyACIDBBAXRqLwEAITsgMEEBaiEwIAIgMUEBdGovAQAhPCAxQQFqITEgPCA5ayAsbCA6IDtrIC1saiA5IDprIC5saiE9IDtBBHQgPUEIakEEdWohPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwUgLiAtTiAtICxOcQRAICEgI2ogJWogJmohMSAgICNqICVqICZqITIgICAiaiAlaiAmaiE0QQAhOANAIAIgMkEBdGovAQAhOSAyQQFqITIgAiA0QQF0ai8BACE6IDRBAWohNCACIDBBAXRqLwEAITsgMEEBaiEwIAIgMUEBdGovAQAhPCAxQQFqITEgPCA5ayAsbCA5IDprIC1saiA6IDtrIC5saiE9IDtBBHQgPUEIakEEdWohPiA+IDggNSA2ICogKyAvICkgECAEIBUQACEVIDhBAWoiOCAESA0ACwVBACE4A0AgAiAwQQF0ai8BACE7IDBBAWohMCA7QQR0IT4gPiA4IDUgNiAqICsgLyApIBAgBCAVEAAhFSA4QQFqIjggBEgNAAsLCwsLCwsgNUUgNnEEQCAmIAhqISZBASE1QQIhNwwBCwwBCwsgKkUgK3EEQCAnIChqIA5qISZBACE1IDYhN0EBISoMAQsMAQsLQQEhRSBBIUMgQiFEIBUgRmshSAsgEkECRgRAIBUgFC0AADoAACAVQQFqIRUgFEEBaiEUBSASQQFGBEAgFUH/AToAACAVQQFqIRULIBQgEWohFAsgE0EBaiETDAALCws=';

function decode(b64) {
    if (typeof Buffer !== 'undefined' && typeof Buffer.from === 'function') {
        return new Uint8Array(Buffer.from(b64, 'base64'));
    }
    if (typeof atob === 'function') {
        const bin = atob(b64);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
    }
    throw new Error('No base64 decoder available (need Buffer or atob).');
}

module.exports = decode(BASE64);
