#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * bench/lcms_compat/run.js — jsColorEngine vs lcms2 .it8 oracle comparison.
 *
 * Walks every `.it8` reference file in `./reference/`, parses it as
 * CGATS.17, decodes the (source, destination, intent, BPC) test config from
 * the filename, loads the matching profile from `./profiles/` (or uses jsCE's
 * built-in virtuals for `srgb` / `lab`), runs each row through
 * `t.forward()` on the float / objectFloat accuracy path, then diffs the
 * answer against the reference column for that row.
 *
 *   Per-file metrics:
 *     - max / mean / p50 / p95 / p99 of the in-gamut error
 *     - error metric is ΔE76 for Lab outputs, max-abs-delta-per-channel
 *       (in the destination profile's native units — 0–255 for RGB and
 *       GRAY, 0–100 % for CMYK, 0–1 for 2CLR / 3CLR / XYZ-PCS) otherwise
 *     - count of samples over a "tight" threshold (0.5 LSB for u8 channels;
 *       0.5 ΔE for Lab; 0.05 % for CMYK ink) so we can flag drift
 *     - separate count of OOG (out-of-gamut) samples — see notes below
 *
 *   Aggregate metrics:
 *     - rolled up by direction (src → dst label) across all 5 intents
 *
 * Why the .it8 oracle is bit-tight to lcms's float pipeline (NOT u16):
 *
 *   The very first sample in srgb_virt_to_lab_Relative.it8 reads
 *   `(0,0,0) → (0.0, 0.00000757, 0.00000757)`. A `7.57e-6` Lab a/b residual
 *   is **three orders of magnitude smaller than the smallest non-zero
 *   value representable in TYPE_Lab_16** (255/65535 ≈ 4e-3). Conclusion:
 *   the references were generated by `transicc` running with `lIsFloat`
 *   enabled — i.e. `cmsCreateTransform(... TYPE_RGB_DBL ... TYPE_Lab_DBL ...)`.
 *   So the comparison here is a like-for-like full-f64 jsCE-vs-lcms
 *   oracle — any drift we see is a real algorithmic disagreement, not
 *   a quantisation artefact on lcms's side.
 *
 * Why OOG samples need a separate bucket:
 *
 *   lcms's float pipeline (TYPE_*_DBL) emits unclamped per-channel values
 *   for out-of-gamut conversions — e.g. `Lab(0,-100,-100) → sRGB` produces
 *   `(-602, +50, +149)` in 0..255 RGB units, which is meaningful in
 *   "what the matrix maths would say with no clamp" terms but not a
 *   real RGB colour. jsCE's accuracy-path output for the same row clamps
 *   the float result to [0,1] before scaling. Comparing clamped to
 *   unclamped gives huge meaningless deltas on the OOG samples and would
 *   dominate the headline. The harness drops any row where ANY reference
 *   channel falls outside the device's native range (< 0 or > native_max
 *   for clamping devices) and reports the OOG count alongside the
 *   in-gamut numbers. Lab outputs are conceptually unbounded so they are
 *   never filtered.
 *
 * Profile coverage:
 *
 *   Drop matching `.icc` / `.icm` / `.ICC` files into `./profiles/`
 *   (gitignored). Filenames must match what the reference set was
 *   generated against — see `profiles/README.md` for the canonical list.
 *   Missing profiles → that test logs as SKIP and the harness moves on.
 *
 * Compile() integration is a follow-up (TODO) — first cut focuses on
 * runtime `t.forward()` to nail the headline numbers.
 *
 * Usage:
 *
 *     node bench/lcms_compat/run.js
 *     node bench/lcms_compat/run.js --quiet            # no per-file lines
 *     node bench/lcms_compat/run.js --filter Lab       # only files whose
 *                                                       config string matches
 *     node bench/lcms_compat/run.js --no-md            # skip last-run.md write
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const { Transform, eIntent, convert } = require('../../src/main');
const Profile = require('../../src/Profile');
const { parseCGATS, rowToInput } = require('./parse-cgats');

// --------------------------------------------------------------------------
//  CLI args
// --------------------------------------------------------------------------

const argv     = process.argv.slice(2);
const flag     = (name) => argv.includes(name);
const argVal   = (name, def) => {
    const i = argv.indexOf(name);
    return (i >= 0 && i + 1 < argv.length) ? argv[i + 1] : def;
};
const QUIET    = flag('--quiet');
const NO_MD    = flag('--no-md');
const FILTER   = argVal('--filter', null);

// --------------------------------------------------------------------------
//  Paths
// --------------------------------------------------------------------------

const REF_DIR      = path.join(__dirname, 'reference');
const PROFILES_DIR = path.join(__dirname, 'profiles');
const REPORT_PATH  = path.join(__dirname, 'last-run.md');

// --------------------------------------------------------------------------
//  Filename → test-config decoder
//
//    `<src>_to_<dst>_<intent>(_BPC)?.it8`
//
//  Where each of `<src>` / `<dst>` is either:
//    - a literal `.icc` / `.icm` / `.ICC` filename (loaded from profiles/)
//    - `srgb` / `srgb_virt`               → jsCE virtual `*sRGB`
//    - `lab`                              → jsCE virtual `*Lab` (D50)
//
//  Intent suffixes are tried longest-first so `_Relative_BPC` wins over
//  `_Relative`. `Saturation` is included for completeness even though the
//  current reference set doesn't ship it (lcms collapses Saturation to
//  Perceptual on most matrix-shaper profiles, so it'd duplicate data).
// --------------------------------------------------------------------------

const INTENT_SUFFIXES = [
    { suffix: '_Relative_BPC',   intent: eIntent.relative,   bpc: true,  name: 'Relative+BPC' },
    { suffix: '_Perceptual_BPC', intent: eIntent.perceptual, bpc: true,  name: 'Perceptual+BPC' },
    { suffix: '_Relative',       intent: eIntent.relative,   bpc: false, name: 'Relative' },
    { suffix: '_Perceptual',     intent: eIntent.perceptual, bpc: false, name: 'Perceptual' },
    { suffix: '_Saturation',     intent: eIntent.saturation, bpc: false, name: 'Saturation' },
    { suffix: '_Absolute',       intent: eIntent.absolute,   bpc: false, name: 'Absolute' },
];

function parseFilename(filename) {
    const base = filename.replace(/\.it8$/, '');

    let intentInfo = null;
    let stripped   = null;
    for (const ii of INTENT_SUFFIXES) {
        if (base.endsWith(ii.suffix)) {
            intentInfo = ii;
            stripped   = base.slice(0, -ii.suffix.length);
            break;
        }
    }
    if (!intentInfo) return { error: 'no intent suffix matched', filename };

    const idx = stripped.indexOf('_to_');
    if (idx < 0) return { error: '"_to_" not found', filename };

    const srcRaw = stripped.slice(0, idx);
    const dstRaw = stripped.slice(idx + 4);

    return {
        filename,
        srcRaw,
        dstRaw,
        srcSpec: resolveSpec(srcRaw),
        dstSpec: resolveSpec(dstRaw),
        intent:  intentInfo.intent,
        bpc:     intentInfo.bpc,
        intentName: intentInfo.name,
    };
}

function resolveSpec(name) {
    const lower = name.toLowerCase();
    if (lower === 'srgb' || lower === 'srgb_virt')          return { kind: 'virt', spec: '*sRGB', label: name };
    if (lower === 'lab'  || lower === 'labd50' || lower === 'lab_virt')
                                                            return { kind: 'virt', spec: '*Lab',  label: name };
    return {
        kind: 'file',
        spec: 'file:' + path.join(PROFILES_DIR, name),
        label: name,
        file:  path.join(PROFILES_DIR, name),
    };
}

// --------------------------------------------------------------------------
//  Profile loader (returns null on miss)
// --------------------------------------------------------------------------

async function loadProfile(spec) {
    if (spec.kind === 'file' && !fs.existsSync(spec.file)) {
        return { profile: null, reason: 'file not found' };
    }
    const p = new Profile();
    try {
        await p.loadPromise(spec.spec);
    } catch (e) {
        return { profile: null, reason: 'load threw: ' + (e.message || e) };
    }
    if (!p.loaded) return { profile: null, reason: 'load returned !loaded' };
    return { profile: p, reason: null };
}

// --------------------------------------------------------------------------
//  Output extractor — pull the expected output channels from a CGATS row
//  in the destination profile's native units (matching what lcms's
//  transicc emits: 0–255 for RGB, 0–100 for CMYK, 0–1 for GRAY / 2CLR /
//  XYZ-PCS, native L 0–100 / a,b ±128 for Lab).
//
//  Returns a plain numeric array so we can iterate uniformly. The
//  XYZ destination is special: lcms's transicc labels its 3 columns
//  `OUT_RGB_R/G/B` even when the profile is XYZ (since both have 3
//  channels and the writer picks "RGB" as the default 3-channel label).
//  We honour that by reading OUT_RGB_* when the dst profile says XYZ.
// --------------------------------------------------------------------------

function extractExpected(row, colorSpace) {
    switch (colorSpace) {
        case 'LAB':
            return [
                firstOf(row, 'OUT_LAB_L', 'OUT_L'),
                firstOf(row, 'OUT_LAB_A', 'OUT_A'),
                firstOf(row, 'OUT_LAB_B', 'OUT_B'),
            ];
        case 'RGB':
            return [row.OUT_RGB_R, row.OUT_RGB_G, row.OUT_RGB_B];
        case 'CMYK':
            return [row.OUT_CMYK_C, row.OUT_CMYK_M, row.OUT_CMYK_Y, row.OUT_CMYK_K];
        case 'GRAY':
            return [firstOf(row, 'OUT_GRAY', 'OUT_G')];
        case '2CLR':
            return [row.OUT_CH1, row.OUT_CH2];
        case '3CLR':
            return [row.OUT_CH1, row.OUT_CH2, row.OUT_CH3];
        case 'XYZ':
            // transicc labels XYZ output columns as OUT_RGB_R/G/B (the
            // generic "3-channel" label). The values are PCS-XYZ floats
            // with Y normalised to 1.0 at white.
            return [
                firstOf(row, 'OUT_XYZ_X', 'OUT_RGB_R'),
                firstOf(row, 'OUT_XYZ_Y', 'OUT_RGB_G'),
                firstOf(row, 'OUT_XYZ_Z', 'OUT_RGB_B'),
            ];
        default:
            throw new Error('extractExpected: unsupported colorSpace "' + colorSpace + '"');
    }
}

function firstOf(row, ...keys) {
    for (const k of keys) {
        if (k in row) return row[k];
    }
    throw new Error('CGATS row missing all of: ' + keys.join(', '));
}

// --------------------------------------------------------------------------
//  Output normaliser — pull the channels out of the jsCE result object
//  and convert into the SAME unit system that extractExpected() returns.
//
//  jsCE on `objectFloat` returns:
//    LAB  → { L, a, b, ... }                (native — match)
//    RGB  → { Rf, Gf, Bf, ... }             (0..1 — multiply by 255)
//    CMYK → { Cf, Mf, Yf, Kf, ... }         (0..1 — multiply by 100)
//    GRAY → { Gf } or { G }                 (probe-time TBD — we cover both)
//    XYZ  → { X, Y, Z, ... }                (PCS-XYZ — match)
//    2CLR → { ?, ? }                        (rare — TBD; we try a few keys)
// --------------------------------------------------------------------------

function jsceToNativeArray(out, colorSpace) {
    switch (colorSpace) {
        case 'LAB':
            return [out.L, out.a, out.b];
        case 'RGB':
            // objectFloat returns Rf/Gf/Bf (0..1). Scale to lcms's 0..255
            // float-decimal RGB convention.
            return [out.Rf * 255, out.Gf * 255, out.Bf * 255];
        case 'CMYK':
            // objectFloat returns Cf/Mf/Yf/Kf (0..1). Scale to lcms's 0..100
            // ink-percent CMYK convention.
            return [out.Cf * 100, out.Mf * 100, out.Yf * 100, out.Kf * 100];
        case 'GRAY':
            // objectFloat returns Gf (0..1). lcms's transicc emits GRAY in
            // 0..255 (verified empirically — same byte convention as RGB).
            if ('Gf' in out) return [out.Gf * 255];
            if ('G'  in out) return [out.G];
            return [NaN];
        case '2CLR':
            // N-channel spot profiles emit raw 0..1 fractions on both sides
            // (lcms's transicc writes nclr in normalised float). jsCE may
            // expose channels under several keys; take the first matched pair.
            if ('Cf' in out && 'Mf' in out) return [out.Cf, out.Mf];
            if ('a'  in out && 'b'  in out) return [out.a, out.b];
            const k2 = Object.keys(out).filter(k => typeof out[k] === 'number');
            return [out[k2[0]], out[k2[1]]];
        case 'XYZ':
            return [out.X, out.Y, out.Z];
        default:
            return [];
    }
}

// --------------------------------------------------------------------------
//  OOG (out-of-gamut) detector for the REFERENCE row.
//
//  lcms's float pipeline doesn't clamp on output, so for OOG conversions
//  it emits negative or super-saturated channel values in the destination
//  device's native unit system. jsCE clamps these to [0, native_max] on
//  the accuracy path, so the row-level error is meaningless on those
//  samples and would swamp the in-gamut headline. We bucket them out and
//  count them separately. Lab is unbounded conceptually, so never OOG;
//  XYZ is a PCS encoding so we leave it un-filtered for now.
// --------------------------------------------------------------------------

function isExpectedOOG(expected, colorSpace) {
    let lo, hi;
    switch (colorSpace) {
        case 'RGB':  lo = 0; hi = 255; break;
        case 'GRAY': lo = 0; hi = 255; break;
        case 'CMYK': lo = 0; hi = 100; break;
        case '2CLR': lo = 0; hi = 1;   break;
        case '3CLR': lo = 0; hi = 1;   break;
        default: return false; // LAB / XYZ — never OOG
    }
    for (const v of expected) {
        if (v < lo || v > hi) return true;
    }
    return false;
}

// --------------------------------------------------------------------------
//  Per-row error metric.
//
//  Lab → ΔE76 (sqrt of sum of squares). Easy to interpret; ΔE values
//  ≤ 1 are below visibility on a calibrated display.
//
//  Anything else → max absolute per-channel delta in the native unit
//  system. Tighter and more diagnostic than RMS for finding the *worst*
//  channel divergence.
// --------------------------------------------------------------------------

function rowError(actual, expected, colorSpace) {
    if (colorSpace === 'LAB') {
        const dL = actual[0] - expected[0];
        const da = actual[1] - expected[1];
        const db = actual[2] - expected[2];
        return Math.sqrt(dL * dL + da * da + db * db);
    }
    let m = 0;
    for (let i = 0; i < expected.length; i++) {
        const d = Math.abs(actual[i] - expected[i]);
        if (d > m) m = d;
    }
    return m;
}

// --------------------------------------------------------------------------
//  Per-file runner
// --------------------------------------------------------------------------

async function runOne(cfg) {
    const srcLoad = await loadProfile(cfg.srcSpec);
    if (!srcLoad.profile) return { status: 'SKIP', reason: 'src ' + cfg.srcSpec.label + ': ' + srcLoad.reason };

    const dstLoad = await loadProfile(cfg.dstSpec);
    if (!dstLoad.profile) return { status: 'SKIP', reason: 'dst ' + cfg.dstSpec.label + ': ' + dstLoad.reason };

    const src = srcLoad.profile;
    const dst = dstLoad.profile;

    const t = new Transform({ dataFormat: 'objectFloat', BPC: cfg.bpc });
    try {
        t.create(src, dst, cfg.intent);
    } catch (e) {
        return { status: 'ERR', reason: 'create() threw: ' + (e.message || e) };
    }

    let cg;
    try {
        cg = parseCGATS(fs.readFileSync(path.join(REF_DIR, cfg.filename), 'utf8'));
    } catch (e) {
        return { status: 'ERR', reason: 'CGATS parse: ' + (e.message || e) };
    }

    const errors = [];
    let badRows = 0;
    let oogRows = 0;

    for (const row of cg.rows) {
        let inp;
        try {
            inp = rowToInput(row, src.colorSpace, convert);
        } catch (e) {
            badRows++;
            continue;
        }

        let actualObj;
        try {
            actualObj = t.forward(inp.input);
        } catch (e) {
            badRows++;
            continue;
        }

        const expected = extractExpected(row, dst.colorSpace);

        // OOG bucket: drop reference rows that lcms's unclamped float
        // pipeline drove outside the device's native range. jsCE clamps
        // these on output so the row-level error is meaningless; reporting
        // the count is more informative than reporting the noise.
        if (isExpectedOOG(expected, dst.colorSpace)) {
            oogRows++;
            continue;
        }

        const actual = jsceToNativeArray(actualObj, dst.colorSpace);
        const err    = rowError(actual, expected, dst.colorSpace);

        if (Number.isFinite(err)) {
            errors.push(err);
        } else {
            badRows++;
        }
    }

    if (errors.length === 0) {
        return {
            status: 'ERR',
            reason: 'no in-gamut rows: ' + cg.rows.length + ' total, ' +
                    oogRows + ' OOG, ' + badRows + ' bad',
            badRows,
            oogRows,
        };
    }

    errors.sort((a, b) => a - b);
    const n = errors.length;
    const pct = (p) => errors[Math.min(n - 1, Math.floor(p * n))];
    const sum = errors.reduce((a, b) => a + b, 0);

    // Tight thresholds for "this is drifting hard" reporting — chosen at
    // the boundary of "obviously below precision" for each unit system.
    //   - Lab:  ΔE76 0.5 — half the perceptual visibility threshold
    //   - RGB / GRAY: 0.5 LSB at u8 — half a code value
    //   - CMYK: 0.05 % ink — well below dot-gain measurement precision
    //   - 2CLR / XYZ-PCS: 1e-3 in native float — generic "below noise"
    const tightThresh =
        dst.colorSpace === 'LAB'  ? 0.5  :
        dst.colorSpace === 'RGB'  ? 0.5  :
        dst.colorSpace === 'GRAY' ? 0.5  :
        dst.colorSpace === 'CMYK' ? 0.05 :
        1e-3;
    let overTight = 0;
    for (const e of errors) if (e > tightThresh) overTight++;

    return {
        status:    'OK',
        n,
        badRows,
        oogRows,
        max:       errors[n - 1],
        mean:      sum / n,
        p50:       pct(0.50),
        p95:       pct(0.95),
        p99:       pct(0.99),
        overTight,
        tightThresh,
        outSpace:  dst.colorSpace,
        metric:    dst.colorSpace === 'LAB' ? 'dE76' : 'max|d|',
        unitNote:  unitNote(dst.colorSpace),
    };
}

function unitNote(colorSpace) {
    switch (colorSpace) {
        case 'LAB':  return 'dE76 (Lab)';
        case 'RGB':  return 'LSB at u8 (0..255)';
        case 'CMYK': return '% ink (0..100)';
        case 'GRAY': return 'LSB at u8 (0..255)';
        case '2CLR': return 'fraction (0..1)';
        case '3CLR': return 'fraction (0..1)';
        case 'XYZ':  return 'PCS-XYZ (~0..1)';
        default:     return colorSpace;
    }
}

// --------------------------------------------------------------------------
//  Main
// --------------------------------------------------------------------------

async function main() {
    if (!fs.existsSync(REF_DIR)) {
        console.error('reference dir not found: ' + REF_DIR);
        process.exit(1);
    }

    let files = fs.readdirSync(REF_DIR).filter(f => f.endsWith('.it8')).sort();
    if (FILTER) files = files.filter(f => f.includes(FILTER));

    console.log('=== lcms_compat — jsCE float vs lcms float .it8 oracle ===');
    console.log('  reference dir : ' + REF_DIR);
    console.log('  profiles dir  : ' + PROFILES_DIR);
    console.log('  candidates    : ' + files.length);
    if (FILTER) console.log('  filter        : ' + FILTER);
    console.log('');

    const tStart = Date.now();
    const results = [];
    let okCount = 0, skipCount = 0, errCount = 0;

    for (const f of files) {
        const cfg = parseFilename(f);
        if (cfg.error) {
            errCount++;
            console.log('  ?? ' + f + '   (' + cfg.error + ')');
            continue;
        }

        const result = await runOne(cfg);
        result.cfg = cfg;
        results.push(result);

        if (result.status === 'OK') {
            okCount++;
            if (!QUIET) {
                const lhs = '  OK  ' + (cfg.srcSpec.label + ' → ' + cfg.dstSpec.label).padEnd(56) +
                            ' ' + cfg.intentName.padEnd(15);
                const rhs = ' n=' + String(result.n).padStart(5) +
                            ' OOG=' + String(result.oogRows).padStart(5) +
                            '  ' + result.metric + ' max=' + result.max.toExponential(2) +
                            '  p99=' + result.p99.toExponential(2) +
                            '  >'   + result.tightThresh + ': ' + result.overTight;
                console.log(lhs + rhs);
            }
        } else if (result.status === 'SKIP') {
            skipCount++;
            // skips are noisy if you don't have all 27 profiles — keep
            // them quiet by default. Re-enable when troubleshooting.
            // console.log('  -- ' + f + '  (' + result.reason + ')');
        } else {
            errCount++;
            console.log('  !! ' + f + '   ' + result.reason);
        }
    }

    const ms = Date.now() - tStart;

    // ----------------------------------------------------------------------
    //  Aggregates: roll up by (srcSpace → dstSpace) across all intents.
    // ----------------------------------------------------------------------

    const groups = new Map();
    for (const r of results) {
        if (r.status !== 'OK') continue;
        // Use the resolved profile's colorSpace where available — but at this
        // point we've discarded the profile reference. Reconstruct from cfg.
        const key = r.cfg.srcSpec.label + ' → ' + r.cfg.dstSpec.label;
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(r);
    }

    console.log('');
    console.log('=== Summary ===');
    console.log('  files OK     : ' + okCount);
    console.log('  files SKIP   : ' + skipCount + (skipCount ? '   (drop matching .icc into profiles/ to expand coverage)' : ''));
    console.log('  files ERROR  : ' + errCount);
    console.log('  wall-clock   : ' + (ms / 1000).toFixed(2) + ' s');
    console.log('');

    if (groups.size > 0) {
        console.log('  Aggregates by direction (in-gamut only — OOG rows shown separately)');
        console.log('  ' + 'direction'.padEnd(58) + '  files  ' +
                    'max'.padStart(10) + '  ' + 'mean'.padStart(10) + '  ' +
                    'p99'.padStart(10) + '  ' + 'over'.padStart(8) +
                    '  ' + 'OOG'.padStart(8) + '  unit');
        const rolled = [];
        for (const [dir, items] of groups) {
            const mx  = items.reduce((a, b) => Math.max(a, b.max),  0);
            const mn  = items.reduce((a, b) => a + b.mean,          0) / items.length;
            const p99 = items.reduce((a, b) => Math.max(a, b.p99),  0);
            const over = items.reduce((a, b) => a + b.overTight,    0);
            const oog  = items.reduce((a, b) => a + b.oogRows,      0);
            const unit = items[0].unitNote;
            rolled.push({ dir, files: items.length, mx, mn, p99, over, oog, unit });
        }
        rolled.sort((a, b) => a.dir.localeCompare(b.dir));
        for (const r of rolled) {
            console.log('  ' + r.dir.padEnd(58) +
                        '  ' + String(r.files).padStart(5) +
                        '  ' + r.mx.toExponential(2).padStart(10) +
                        '  ' + r.mn.toExponential(2).padStart(10) +
                        '  ' + r.p99.toExponential(2).padStart(10) +
                        '  ' + String(r.over).padStart(8) +
                        '  ' + String(r.oog).padStart(8) +
                        '  ' + r.unit);
        }
    }

    if (!NO_MD) {
        writeMarkdownReport(results, { okCount, skipCount, errCount, ms, files: files.length });
        console.log('');
        console.log('  report       : ' + REPORT_PATH);
    }
}

// --------------------------------------------------------------------------
//  Markdown report — committable artefact so we can track drift across
//  jsCE versions / lcms versions in the diff log.
// --------------------------------------------------------------------------

function writeMarkdownReport(results, stats) {
    const lines = [];
    lines.push('# lcms_compat — last run');
    lines.push('');
    lines.push('Generated by `bench/lcms_compat/run.js` at ' + new Date().toISOString() + '.');
    lines.push('');
    lines.push('Compares `Transform.forward()` (jsCE on the float / objectFloat accuracy path)');
    lines.push('against the reference outputs that `transicc4batch` produced from lcms2 2.16');
    lines.push('with `TYPE_*_DBL` (full f64 pipeline). See `README.md` for the full');
    lines.push('methodology and `lcms_patch/README.md` for the regenerator.');
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    lines.push('| metric | value |');
    lines.push('|---|---|');
    lines.push('| candidate files | ' + stats.files + ' |');
    lines.push('| files OK        | ' + stats.okCount + ' |');
    lines.push('| files SKIP      | ' + stats.skipCount + ' |');
    lines.push('| files ERROR     | ' + stats.errCount + ' |');
    lines.push('| wall-clock      | ' + (stats.ms / 1000).toFixed(2) + ' s |');
    lines.push('');

    // Per-direction roll-up (same as console summary).
    const groups = new Map();
    for (const r of results) {
        if (r.status !== 'OK') continue;
        const key = r.cfg.srcSpec.label + ' → ' + r.cfg.dstSpec.label;
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(r);
    }

    if (groups.size > 0) {
        lines.push('## Aggregates by direction');
        lines.push('');
        lines.push('In-gamut only — see "Why OOG samples need a separate bucket" comment');
        lines.push('in `run.js` for the rationale (lcms float pipeline doesn\'t clamp;');
        lines.push('jsCE accuracy path does, so comparing them on OOG rows is meaningless).');
        lines.push('');
        lines.push('| direction | files | unit | max | mean | p99 | rows over tight thr | OOG rows |');
        lines.push('|---|---:|---|---:|---:|---:|---:|---:|');
        const rolled = [];
        for (const [dir, items] of groups) {
            const mx  = items.reduce((a, b) => Math.max(a, b.max),  0);
            const mn  = items.reduce((a, b) => a + b.mean,          0) / items.length;
            const p99 = items.reduce((a, b) => Math.max(a, b.p99),  0);
            const over = items.reduce((a, b) => a + b.overTight,    0);
            const oog  = items.reduce((a, b) => a + b.oogRows,      0);
            const unit = items[0].unitNote;
            rolled.push({ dir, files: items.length, unit, mx, mn, p99, over, oog });
        }
        rolled.sort((a, b) => a.dir.localeCompare(b.dir));
        for (const r of rolled) {
            lines.push('| ' + r.dir + ' | ' + r.files + ' | ' +
                       r.unit + ' | ' +
                       r.mx.toExponential(2) + ' | ' +
                       r.mn.toExponential(2) + ' | ' +
                       r.p99.toExponential(2) + ' | ' +
                       r.over + ' | ' +
                       r.oog + ' |');
        }
        lines.push('');
    }

    lines.push('## Per-file detail (OK only)');
    lines.push('');
    lines.push('| file | n | OOG | max | mean | p50 | p95 | p99 | rows over tight thr |');
    lines.push('|---|---:|---:|---:|---:|---:|---:|---:|---:|');
    const ok = results.filter(r => r.status === 'OK').sort((a, b) => b.max - a.max);
    for (const r of ok) {
        lines.push('| `' + r.cfg.filename + '` | ' + r.n + ' | ' + r.oogRows + ' | ' +
                   r.max.toExponential(2) + ' | ' +
                   r.mean.toExponential(2) + ' | ' +
                   r.p50.toExponential(2) + ' | ' +
                   r.p95.toExponential(2) + ' | ' +
                   r.p99.toExponential(2) + ' | ' +
                   r.overTight + ' |');
    }

    const skipped = results.filter(r => r.status === 'SKIP');
    if (skipped.length > 0) {
        lines.push('');
        lines.push('## Skipped (' + skipped.length + ')');
        lines.push('');
        const reasons = new Map();
        for (const r of skipped) {
            const k = r.reason;
            reasons.set(k, (reasons.get(k) || 0) + 1);
        }
        lines.push('| reason | count |');
        lines.push('|---|---:|');
        for (const [k, v] of [...reasons.entries()].sort((a, b) => b[1] - a[1])) {
            lines.push('| ' + k + ' | ' + v + ' |');
        }
    }

    const errored = results.filter(r => r.status === 'ERR');
    if (errored.length > 0) {
        lines.push('');
        lines.push('## Errored (' + errored.length + ')');
        lines.push('');
        lines.push('| file | reason |');
        lines.push('|---|---|');
        for (const r of errored) {
            lines.push('| `' + r.cfg.filename + '` | ' + r.reason + ' |');
        }
    }

    fs.writeFileSync(REPORT_PATH, lines.join('\n') + '\n');
}

main().catch(e => { console.error(e); process.exit(1); });
