/*************************************************************************
 *  @license
 *
 *  Copyright © 2019, 2026 Glenn Wilton
 *  O2 Creative Limited
 *************************************************************************/

// ============================================================================
// tetra3d_nch.wasm.js — AUTO-GENERATED from tetra3d_nch.wat
// ============================================================================
//
// Do not edit by hand. Regenerate with:
//   node scripts/compile_kernel_wat.js src/kernels/3d/tetra3d_nch.wat
//
// Exports: interp_tetra3d_nCh (verbatim) + interp_tetra3d_nCh_cached (single-entry).
// Source:  src/kernels/3d/tetra3d_nch.wat
// Size:    3847 bytes .wasm
// ============================================================================

'use strict';

const BASE64 = 'AGFzbQEAAAABEgFgDn9/f39/f39/f39/f39/AAMDAgAABQMBAAEHOwMGbWVtb3J5AgASaW50ZXJwX3RldHJhM2RfbkNoAAAZaW50ZXJwX3RldHJhM2RfbkNoX2NhY2hlZAABCqEdAqAOAR9/IAAhDyABIRACQANAIA4gA04NASAPLQAAIREgD0EBai0AACESIA9BAmotAAAhEyAPQQNqIQ8gESAIbCEUIBIgCGwhFSATIAhsIRYgEUH/AUYEQCAJIRcgCSEYQQAhHQUgFEEQdiAHbCEXIBcgB2ohGCAUQQh2Qf8BcSEdCyASQf8BRgRAIAohGSAKIRpBACEeBSAVQRB2IAZsIRkgGSAGaiEaIBVBCHZB/wFxIR4LIBNB/wFGBEAgCyEbIAshHEEAIR8FIBZBEHYgBWwhGyAbIAVqIRwgFkEIdkH/AXEhHwsgFyAZaiAbaiEgIB0gHk4gHiAfTnEEQCAYIBlqIBtqISEgGCAaaiAbaiEiIBggGmogHGohJEEAISUDQCACICFBAXRqLwEAISYgIUEBaiEhIAIgIkEBdGovAQAhJyAiQQFqISIgAiAgQQF0ai8BACEoICBBAWohICACICRBAXRqLwEAISkgJEEBaiEkICYgKGsgHWwgJyAmayAebGogKSAnayAfbGohKiAoICpBgAFqQQh1aiErICtBgAFqQQh1ISwgLEEAICxBAE4bISwgLEH/ASAsQYACSBshLCAQICw6AAAgEEEBaiEQICVBAWoiJSAESA0ACwUgHSAfTiAfIB5OcQRAIBggGWogG2ohISAYIBpqIBxqISIgGCAZaiAcaiEjQQAhJQNAIAIgI0EBdGovAQAhJiAjQQFqISMgAiAhQQF0ai8BACEnICFBAWohISACICBBAXRqLwEAISggIEEBaiEgIAIgIkEBdGovAQAhKSAiQQFqISIgJyAoayAdbCApICZrIB5saiAmICdrIB9saiEqICggKkGAAWpBCHVqISsgK0GAAWpBCHUhLCAsQQAgLEEAThshLCAsQf8BICxBgAJIGyEsIBAgLDoAACAQQQFqIRAgJUEBaiIlIARIDQALBSAdIB5OIB8gHU5xBEAgGCAZaiAcaiEhIBcgGWogHGohIiAYIBpqIBxqISNBACElA0AgAiAhQQF0ai8BACEmICFBAWohISACICJBAXRqLwEAIScgIkEBaiEiIAIgIEEBdGovAQAhKCAgQQFqISAgAiAjQQF0ai8BACEpICNBAWohIyAmICdrIB1sICkgJmsgHmxqICcgKGsgH2xqISogKCAqQYABakEIdWohKyArQYABakEIdSEsICxBACAsQQBOGyEsICxB/wEgLEGAAkgbISwgECAsOgAAIBBBAWohECAlQQFqIiUgBEgNAAsFIB4gHU4gHSAfTnEEQCAYIBpqIBtqISEgFyAaaiAbaiEiIBggGmogHGohJEEAISUDQCACICJBAXRqLwEAISYgIkEBaiEiIAIgIUEBdGovAQAhJyAhQQFqISEgAiAgQQF0ai8BACEoICBBAWohICACICRBAXRqLwEAISkgJEEBaiEkICcgJmsgHWwgJiAoayAebGogKSAnayAfbGohKiAoICpBgAFqQQh1aiErICtBgAFqQQh1ISwgLEEAICxBAE4bISwgLEH/ASAsQYACSBshLCAQICw6AAAgEEEBaiEQICVBAWoiJSAESA0ACwUgHiAfTiAfIB1OcQRAIBggGmogHGohISAXIBpqIBxqISIgFyAaaiAbaiEjQQAhJQNAIAIgIkEBdGovAQAhJiAiQQFqISIgAiAjQQF0ai8BACEnICNBAWohIyACICBBAXRqLwEAISggIEEBaiEgIAIgIUEBdGovAQAhKSAhQQFqISEgKSAmayAdbCAnIChrIB5saiAmICdrIB9saiEqICggKkGAAWpBCHVqISsgK0GAAWpBCHUhLCAsQQAgLEEAThshLCAsQf8BICxBgAJIGyEsIBAgLDoAACAQQQFqIRAgJUEBaiIlIARIDQALBSAfIB5OIB4gHU5xBEAgGCAaaiAcaiEhIBcgGmogHGohIiAXIBlqIBxqISRBACElA0AgAiAiQQF0ai8BACEmICJBAWohIiACICRBAXRqLwEAIScgJEEBaiEkIAIgIEEBdGovAQAhKCAgQQFqISAgAiAhQQF0ai8BACEpICFBAWohISApICZrIB1sICYgJ2sgHmxqICcgKGsgH2xqISogKCAqQYABakEIdWohKyArQYABakEIdSEsICxBACAsQQBOGyEsICxB/wEgLEGAAkgbISwgECAsOgAAIBBBAWohECAlQQFqIiUgBEgNAAsFQQAhJQNAIAIgIEEBdGovAQAhKCAgQQFqISAgKEGAAWpBCHUhLCAsQQAgLEEAThshLCAsQf8BICxBgAJIGyEsIBAgLDoAACAQQQFqIRAgJUEBaiIlIARIDQALCwsLCwsLIA1BAkYEQCAQIA8tAAA6AAAgEEEBaiEQIA9BAWohDwUgDUEBRgRAIBBB/wE6AAAgEEEBaiEQCyAPIAxqIQ8LIA5BAWohDgwACwsL/A4BJH8gACEPIAEhEEF/IS4gBCEvAkADQCAOIANODQEgDy0AACERIA9BAWotAAAhEiAPQQJqLQAAIRMgD0EDaiEPIBFBEHQgEkEIdHIgE3IhLQJAIC0gLkYEQEEAITADQCAQIDBqIDEgMGotAAA6AAAgMEEBaiEwIDAgL0kNAAsgECAvaiEQDAELIBEgCGwhFCASIAhsIRUgEyAIbCEWIBFB/wFGBEAgCSEXIAkhGEEAIR0FIBRBEHYgB2whFyAXIAdqIRggFEEIdkH/AXEhHQsgEkH/AUYEQCAKIRkgCiEaQQAhHgUgFUEQdiAGbCEZIBkgBmohGiAVQQh2Qf8BcSEeCyATQf8BRgRAIAshGyALIRxBACEfBSAWQRB2IAVsIRsgGyAFaiEcIBZBCHZB/wFxIR8LIBcgGWogG2ohICAdIB5OIB4gH05xBEAgGCAZaiAbaiEhIBggGmogG2ohIiAYIBpqIBxqISRBACElA0AgAiAhQQF0ai8BACEmICFBAWohISACICJBAXRqLwEAIScgIkEBaiEiIAIgIEEBdGovAQAhKCAgQQFqISAgAiAkQQF0ai8BACEpICRBAWohJCAmIChrIB1sICcgJmsgHmxqICkgJ2sgH2xqISogKCAqQYABakEIdWohKyArQYABakEIdSEsICxBACAsQQBOGyEsICxB/wEgLEGAAkgbISwgECAsOgAAIBBBAWohECAlQQFqIiUgBEgNAAsFIB0gH04gHyAeTnEEQCAYIBlqIBtqISEgGCAaaiAcaiEiIBggGWogHGohI0EAISUDQCACICNBAXRqLwEAISYgI0EBaiEjIAIgIUEBdGovAQAhJyAhQQFqISEgAiAgQQF0ai8BACEoICBBAWohICACICJBAXRqLwEAISkgIkEBaiEiICcgKGsgHWwgKSAmayAebGogJiAnayAfbGohKiAoICpBgAFqQQh1aiErICtBgAFqQQh1ISwgLEEAICxBAE4bISwgLEH/ASAsQYACSBshLCAQICw6AAAgEEEBaiEQICVBAWoiJSAESA0ACwUgHSAeTiAfIB1OcQRAIBggGWogHGohISAXIBlqIBxqISIgGCAaaiAcaiEjQQAhJQNAIAIgIUEBdGovAQAhJiAhQQFqISEgAiAiQQF0ai8BACEnICJBAWohIiACICBBAXRqLwEAISggIEEBaiEgIAIgI0EBdGovAQAhKSAjQQFqISMgJiAnayAdbCApICZrIB5saiAnIChrIB9saiEqICggKkGAAWpBCHVqISsgK0GAAWpBCHUhLCAsQQAgLEEAThshLCAsQf8BICxBgAJIGyEsIBAgLDoAACAQQQFqIRAgJUEBaiIlIARIDQALBSAeIB1OIB0gH05xBEAgGCAaaiAbaiEhIBcgGmogG2ohIiAYIBpqIBxqISRBACElA0AgAiAiQQF0ai8BACEmICJBAWohIiACICFBAXRqLwEAIScgIUEBaiEhIAIgIEEBdGovAQAhKCAgQQFqISAgAiAkQQF0ai8BACEpICRBAWohJCAnICZrIB1sICYgKGsgHmxqICkgJ2sgH2xqISogKCAqQYABakEIdWohKyArQYABakEIdSEsICxBACAsQQBOGyEsICxB/wEgLEGAAkgbISwgECAsOgAAIBBBAWohECAlQQFqIiUgBEgNAAsFIB4gH04gHyAdTnEEQCAYIBpqIBxqISEgFyAaaiAcaiEiIBcgGmogG2ohI0EAISUDQCACICJBAXRqLwEAISYgIkEBaiEiIAIgI0EBdGovAQAhJyAjQQFqISMgAiAgQQF0ai8BACEoICBBAWohICACICFBAXRqLwEAISkgIUEBaiEhICkgJmsgHWwgJyAoayAebGogJiAnayAfbGohKiAoICpBgAFqQQh1aiErICtBgAFqQQh1ISwgLEEAICxBAE4bISwgLEH/ASAsQYACSBshLCAQICw6AAAgEEEBaiEQICVBAWoiJSAESA0ACwUgHyAeTiAeIB1OcQRAIBggGmogHGohISAXIBpqIBxqISIgFyAZaiAcaiEkQQAhJQNAIAIgIkEBdGovAQAhJiAiQQFqISIgAiAkQQF0ai8BACEnICRBAWohJCACICBBAXRqLwEAISggIEEBaiEgIAIgIUEBdGovAQAhKSAhQQFqISEgKSAmayAdbCAmICdrIB5saiAnIChrIB9saiEqICggKkGAAWpBCHVqISsgK0GAAWpBCHUhLCAsQQAgLEEAThshLCAsQf8BICxBgAJIGyEsIBAgLDoAACAQQQFqIRAgJUEBaiIlIARIDQALBUEAISUDQCACICBBAXRqLwEAISggIEEBaiEgIChBgAFqQQh1ISwgLEEAICxBAE4bISwgLEH/ASAsQYACSBshLCAQICw6AAAgEEEBaiEQICVBAWoiJSAESA0ACwsLCwsLCyAtIS4gECAvayExCyANQQJGBEAgECAPLQAAOgAAIBBBAWohECAPQQFqIQ8FIA1BAUYEQCAQQf8BOgAAIBBBAWohEAsgDyAMaiEPCyAOQQFqIQ4MAAsLCw==';

function decode(b64) {
    if (typeof Buffer !== 'undefined' && typeof Buffer.from === 'function') {
        return new Uint8Array(Buffer.from(b64, 'base64'));
    }
    if (typeof atob === 'function') {
        const bin = atob(b64);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
    }
    throw new Error('No base64 decoder available (need Buffer or atob).');
}

module.exports = decode(BASE64);
