/*************************************************************************
 *  @license
 *
 *  Copyright © 2019, 2026 Glenn Wilton
 *  O2 Creative Limited
 *************************************************************************/

// ============================================================================
// tetra3d_simd_int16.wasm.js — AUTO-GENERATED from tetra3d_simd_int16.wat
// ============================================================================
//
// Do not edit by hand. Regenerate with:
//   node scripts/compile_kernel_wat.js src/kernels/3d/tetra3d_simd_int16.wat
//
// Exports: interp_tetra3d_simd_int16 (verbatim) + interp_tetra3d_simd_int16_cached (single-entry).
// Source:  src/kernels/3d/tetra3d_simd_int16.wat
// Size:    2749 bytes .wasm
// ============================================================================

'use strict';

const BASE64 = 'AGFzbQEAAAABEgFgDn9/f39/f39/f39/f39/AAMDAgAABQMBAAEHSQMGbWVtb3J5AgAZaW50ZXJwX3RldHJhM2Rfc2ltZF9pbnQxNgAAIGludGVycF90ZXRyYTNkX3NpbWRfaW50MTZfY2FjaGVkAAEKyRQC/AkCGH8KeyAAIQ8gASEQIARBAXQhEQJAA0AgDiADTg0BIA8vAQAhEiAPLwECIRMgDy8BBCEUIA9BBmohDyASIAhsIRUgEyAIbCEWIBQgCGwhFyASQf//A0YEQCAJIRggCSEZQQAhHgUgFUENdiAHbCEYIBggB2ohGSAVQf8/cSEeCyATQf//A0YEQCAKIRogCiEbQQAhHwUgFkENdiAGbCEaIBogBmohGyAWQf8/cSEfCyAUQf//A0YEQCALIRwgCyEdQQAhIAUgF0ENdiAFbCEcIBwgBWohHSAXQf8/cSEgCyAe/REhKiAf/REhKyAg/REhLCAYIBpqIBxqISEgAiAhQQF0av1dAAD9qQEhKCAeIB9OIB8gIE5xBEAgGSAaaiAcaiEiIBkgG2ogHGohIyAZIBtqIB1qISUgAiAiQQF0av1dAAD9qQEhJiACICNBAXRq/V0AAP2pASEnIAIgJUEBdGr9XQAA/akBISkgJiAo/bEBICr9tQEgJyAm/bEBICv9tQH9rgEgKSAn/bEBICz9tQH9rgEhLQUgHiAgTiAgIB9OcQRAIBkgGmogHGohIiAZIBtqIB1qISMgGSAaaiAdaiEkIAIgJEEBdGr9XQAA/akBISYgAiAiQQF0av1dAAD9qQEhJyACICNBAXRq/V0AAP2pASEpICcgKP2xASAq/bUBICkgJv2xASAr/bUB/a4BICYgJ/2xASAs/bUB/a4BIS0FIB4gH04gICAeTnEEQCAZIBpqIB1qISIgGCAaaiAdaiEjIBkgG2ogHWohJCACICJBAXRq/V0AAP2pASEmIAIgI0EBdGr9XQAA/akBIScgAiAkQQF0av1dAAD9qQEhKSAmICf9sQEgKv21ASApICb9sQEgK/21Af2uASAnICj9sQEgLP21Af2uASEtBSAfIB5OIB4gIE5xBEAgGSAbaiAcaiEiIBggG2ogHGohIyAZIBtqIB1qISUgAiAjQQF0av1dAAD9qQEhJiACICJBAXRq/V0AAP2pASEnIAIgJUEBdGr9XQAA/akBISkgJyAm/bEBICr9tQEgJiAo/bEBICv9tQH9rgEgKSAn/bEBICz9tQH9rgEhLQUgHyAgTiAgIB5OcQRAIBkgG2ogHWohIiAYIBtqIB1qISMgGCAbaiAcaiEkIAIgI0EBdGr9XQAA/akBISYgAiAkQQF0av1dAAD9qQEhJyACICJBAXRq/V0AAP2pASEpICkgJv2xASAq/bUBICcgKP2xASAr/bUB/a4BICYgJ/2xASAs/bUB/a4BIS0FICAgH04gHyAeTnEEQCAZIBtqIB1qISIgGCAbaiAdaiEjIBggGmogHWohJSACICNBAXRq/V0AAP2pASEmIAIgJUEBdGr9XQAA/akBIScgAiAiQQF0av1dAAD9qQEhKSApICb9sQEgKv21ASAmICf9sQEgK/21Af2uASAnICj9sQEgLP21Af2uASEtBf0MAAAAAAAAAAAAAAAAAAAAACEtCwsLCwsLICggLf0MABAAAAAQAAAAEAAAABAAAP2uAUEN/awB/a4BIS4gLiAu/YYBIS8gECAv/VsAAAAgECARaiEQIA0gDHIEQCANQQJGBEAgECAPLwEAOwEAIBBBAmohECAPQQJqIQ8FIA1BAUYEQCAQQf//AzsBACAQQQJqIRALIA8gDEEBdGohDwsLIA5BAWohDgwACwsLyAoEGH8KewV/AXsgACEPIAEhECAEQQF0IRFBACE0AkADQCAOIANODQEgDy8BACESIA8vAQIhEyAPLwEEIRQgD0EGaiEPIBIgE0EQdHIhMCAUITECQCA0IDAgMkYgMSAzRnFxBEAgECA1/VsAAAAgECARaiEQDAELIBIgCGwhFSATIAhsIRYgFCAIbCEXIBJB//8DRgRAIAkhGCAJIRlBACEeBSAVQQ12IAdsIRggGCAHaiEZIBVB/z9xIR4LIBNB//8DRgRAIAohGiAKIRtBACEfBSAWQQ12IAZsIRogGiAGaiEbIBZB/z9xIR8LIBRB//8DRgRAIAshHCALIR1BACEgBSAXQQ12IAVsIRwgHCAFaiEdIBdB/z9xISALIB79ESEqIB/9ESErICD9ESEsIBggGmogHGohISACICFBAXRq/V0AAP2pASEoIB4gH04gHyAgTnEEQCAZIBpqIBxqISIgGSAbaiAcaiEjIBkgG2ogHWohJSACICJBAXRq/V0AAP2pASEmIAIgI0EBdGr9XQAA/akBIScgAiAlQQF0av1dAAD9qQEhKSAmICj9sQEgKv21ASAnICb9sQEgK/21Af2uASApICf9sQEgLP21Af2uASEtBSAeICBOICAgH05xBEAgGSAaaiAcaiEiIBkgG2ogHWohIyAZIBpqIB1qISQgAiAkQQF0av1dAAD9qQEhJiACICJBAXRq/V0AAP2pASEnIAIgI0EBdGr9XQAA/akBISkgJyAo/bEBICr9tQEgKSAm/bEBICv9tQH9rgEgJiAn/bEBICz9tQH9rgEhLQUgHiAfTiAgIB5OcQRAIBkgGmogHWohIiAYIBpqIB1qISMgGSAbaiAdaiEkIAIgIkEBdGr9XQAA/akBISYgAiAjQQF0av1dAAD9qQEhJyACICRBAXRq/V0AAP2pASEpICYgJ/2xASAq/bUBICkgJv2xASAr/bUB/a4BICcgKP2xASAs/bUB/a4BIS0FIB8gHk4gHiAgTnEEQCAZIBtqIBxqISIgGCAbaiAcaiEjIBkgG2ogHWohJSACICNBAXRq/V0AAP2pASEmIAIgIkEBdGr9XQAA/akBIScgAiAlQQF0av1dAAD9qQEhKSAnICb9sQEgKv21ASAmICj9sQEgK/21Af2uASApICf9sQEgLP21Af2uASEtBSAfICBOICAgHk5xBEAgGSAbaiAdaiEiIBggG2ogHWohIyAYIBtqIBxqISQgAiAjQQF0av1dAAD9qQEhJiACICRBAXRq/V0AAP2pASEnIAIgIkEBdGr9XQAA/akBISkgKSAm/bEBICr9tQEgJyAo/bEBICv9tQH9rgEgJiAn/bEBICz9tQH9rgEhLQUgICAfTiAfIB5OcQRAIBkgG2ogHWohIiAYIBtqIB1qISMgGCAaaiAdaiElIAIgI0EBdGr9XQAA/akBISYgAiAlQQF0av1dAAD9qQEhJyACICJBAXRq/V0AAP2pASEpICkgJv2xASAq/bUBICYgJ/2xASAr/bUB/a4BICcgKP2xASAs/bUB/a4BIS0F/QwAAAAAAAAAAAAAAAAAAAAAIS0LCwsLCwsgKCAt/QwAEAAAABAAAAAQAAAAEAAA/a4BQQ39rAH9rgEhLiAuIC79hgEhLyAQIC/9WwAAACAQIBFqIRBBASE0IDAhMiAxITMgLyE1CyANIAxyBEAgDUECRgRAIBAgDy8BADsBACAQQQJqIRAgD0ECaiEPBSANQQFGBEAgEEH//wM7AQAgEEECaiEQCyAPIAxBAXRqIQ8LCyAOQQFqIQ4MAAsLCw==';

function decode(b64) {
    if (typeof Buffer !== 'undefined' && typeof Buffer.from === 'function') {
        return new Uint8Array(Buffer.from(b64, 'base64'));
    }
    if (typeof atob === 'function') {
        const bin = atob(b64);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
    }
    throw new Error('No base64 decoder available (need Buffer or atob).');
}

module.exports = decode(BASE64);
