/*************************************************************************
 *  @license
 *
 *  Copyright © 2019, 2026 Glenn Wilton
 *  O2 Creative Limited
 *************************************************************************/

// ============================================================================
// tetra3d_nch_int16.wasm.js — AUTO-GENERATED from tetra3d_nch_int16.wat
// ============================================================================
//
// Do not edit by hand. Regenerate with:
//   node scripts/compile_kernel_wat.js src/kernels/3d/tetra3d_nch_int16.wat
//
// Exports: interp_tetra3d_nCh_int16 (verbatim) + interp_tetra3d_nCh_int16_cached (single-entry).
// Source:  src/kernels/3d/tetra3d_nch_int16.wat
// Size:    3355 bytes .wasm
// ============================================================================

'use strict';

const BASE64 = 'AGFzbQEAAAABEgFgDn9/f39/f39/f39/f39/AAMDAgAABQMBAAEHRwMGbWVtb3J5AgAYaW50ZXJwX3RldHJhM2RfbkNoX2ludDE2AAAfaW50ZXJwX3RldHJhM2RfbkNoX2ludDE2X2NhY2hlZAABCqkZApsMAR5/IAAhDyABIRACQANAIA4gA04NASAPLwEAIREgD0ECai8BACESIA9BBGovAQAhEyAPQQZqIQ8gESAIbCEUIBIgCGwhFSATIAhsIRYgEUH//wNGBEAgCSEXIAkhGEEAIR0FIBRBDXYgB2whFyAXIAdqIRggFEH/P3EhHQsgEkH//wNGBEAgCiEZIAohGkEAIR4FIBVBDXYgBmwhGSAZIAZqIRogFUH/P3EhHgsgE0H//wNGBEAgCyEbIAshHEEAIR8FIBZBDXYgBWwhGyAbIAVqIRwgFkH/P3EhHwsgFyAZaiAbaiEgIB0gHk4gHiAfTnEEQCAYIBlqIBtqISEgGCAaaiAbaiEiIBggGmogHGohJEEAISUDQCACICFBAXRqLwEAISYgIUEBaiEhIAIgIkEBdGovAQAhJyAiQQFqISIgAiAgQQF0ai8BACEoICBBAWohICACICRBAXRqLwEAISkgJEEBaiEkICYgKGsgHWwgJyAmayAebGogKSAnayAfbGohKiAoICpBgCBqQQ11aiErIBAgKzsBACAQQQJqIRAgJUEBaiIlIARIDQALBSAdIB9OIB8gHk5xBEAgGCAZaiAbaiEhIBggGmogHGohIiAYIBlqIBxqISNBACElA0AgAiAjQQF0ai8BACEmICNBAWohIyACICFBAXRqLwEAIScgIUEBaiEhIAIgIEEBdGovAQAhKCAgQQFqISAgAiAiQQF0ai8BACEpICJBAWohIiAnIChrIB1sICkgJmsgHmxqICYgJ2sgH2xqISogKCAqQYAgakENdWohKyAQICs7AQAgEEECaiEQICVBAWoiJSAESA0ACwUgHSAeTiAfIB1OcQRAIBggGWogHGohISAXIBlqIBxqISIgGCAaaiAcaiEjQQAhJQNAIAIgIUEBdGovAQAhJiAhQQFqISEgAiAiQQF0ai8BACEnICJBAWohIiACICBBAXRqLwEAISggIEEBaiEgIAIgI0EBdGovAQAhKSAjQQFqISMgJiAnayAdbCApICZrIB5saiAnIChrIB9saiEqICggKkGAIGpBDXVqISsgECArOwEAIBBBAmohECAlQQFqIiUgBEgNAAsFIB4gHU4gHSAfTnEEQCAYIBpqIBtqISEgFyAaaiAbaiEiIBggGmogHGohJEEAISUDQCACICJBAXRqLwEAISYgIkEBaiEiIAIgIUEBdGovAQAhJyAhQQFqISEgAiAgQQF0ai8BACEoICBBAWohICACICRBAXRqLwEAISkgJEEBaiEkICcgJmsgHWwgJiAoayAebGogKSAnayAfbGohKiAoICpBgCBqQQ11aiErIBAgKzsBACAQQQJqIRAgJUEBaiIlIARIDQALBSAeIB9OIB8gHU5xBEAgGCAaaiAcaiEhIBcgGmogHGohIiAXIBpqIBtqISNBACElA0AgAiAiQQF0ai8BACEmICJBAWohIiACICNBAXRqLwEAIScgI0EBaiEjIAIgIEEBdGovAQAhKCAgQQFqISAgAiAhQQF0ai8BACEpICFBAWohISApICZrIB1sICcgKGsgHmxqICYgJ2sgH2xqISogKCAqQYAgakENdWohKyAQICs7AQAgEEECaiEQICVBAWoiJSAESA0ACwUgHyAeTiAeIB1OcQRAIBggGmogHGohISAXIBpqIBxqISIgFyAZaiAcaiEkQQAhJQNAIAIgIkEBdGovAQAhJiAiQQFqISIgAiAkQQF0ai8BACEnICRBAWohJCACICBBAXRqLwEAISggIEEBaiEgIAIgIUEBdGovAQAhKSAhQQFqISEgKSAmayAdbCAmICdrIB5saiAnIChrIB9saiEqICggKkGAIGpBDXVqISsgECArOwEAIBBBAmohECAlQQFqIiUgBEgNAAsFQQAhJQNAIAIgIEEBdGovAQAhKCAgQQFqISAgECAoOwEAIBBBAmohECAlQQFqIiUgBEgNAAsLCwsLCwsgDUECRgRAIBAgDy8BADsBACAQQQJqIRAgD0ECaiEPBSANQQFGBEAgEEH//wM7AQAgEEECaiEQCyAPIAxBAXRqIQ8LIA5BAWohDgwACwsLiQ0BJn8gACEPIAEhEEEAITAgBEEBdCExAkADQCAOIANODQEgDy8BACERIA9BAmovAQAhEiAPQQRqLwEAIRMgD0EGaiEPIBEgEkEQdHIhLCATIS0CQCAwICwgLkYgLSAvRnFxBEBBACEyA0AgECAyaiAzIDJqLQAAOgAAIDJBAWohMiAyIDFJDQALIBAgMWohEAwBCyARIAhsIRQgEiAIbCEVIBMgCGwhFiARQf//A0YEQCAJIRcgCSEYQQAhHQUgFEENdiAHbCEXIBcgB2ohGCAUQf8/cSEdCyASQf//A0YEQCAKIRkgCiEaQQAhHgUgFUENdiAGbCEZIBkgBmohGiAVQf8/cSEeCyATQf//A0YEQCALIRsgCyEcQQAhHwUgFkENdiAFbCEbIBsgBWohHCAWQf8/cSEfCyAXIBlqIBtqISAgHSAeTiAeIB9OcQRAIBggGWogG2ohISAYIBpqIBtqISIgGCAaaiAcaiEkQQAhJQNAIAIgIUEBdGovAQAhJiAhQQFqISEgAiAiQQF0ai8BACEnICJBAWohIiACICBBAXRqLwEAISggIEEBaiEgIAIgJEEBdGovAQAhKSAkQQFqISQgJiAoayAdbCAnICZrIB5saiApICdrIB9saiEqICggKkGAIGpBDXVqISsgECArOwEAIBBBAmohECAlQQFqIiUgBEgNAAsFIB0gH04gHyAeTnEEQCAYIBlqIBtqISEgGCAaaiAcaiEiIBggGWogHGohI0EAISUDQCACICNBAXRqLwEAISYgI0EBaiEjIAIgIUEBdGovAQAhJyAhQQFqISEgAiAgQQF0ai8BACEoICBBAWohICACICJBAXRqLwEAISkgIkEBaiEiICcgKGsgHWwgKSAmayAebGogJiAnayAfbGohKiAoICpBgCBqQQ11aiErIBAgKzsBACAQQQJqIRAgJUEBaiIlIARIDQALBSAdIB5OIB8gHU5xBEAgGCAZaiAcaiEhIBcgGWogHGohIiAYIBpqIBxqISNBACElA0AgAiAhQQF0ai8BACEmICFBAWohISACICJBAXRqLwEAIScgIkEBaiEiIAIgIEEBdGovAQAhKCAgQQFqISAgAiAjQQF0ai8BACEpICNBAWohIyAmICdrIB1sICkgJmsgHmxqICcgKGsgH2xqISogKCAqQYAgakENdWohKyAQICs7AQAgEEECaiEQICVBAWoiJSAESA0ACwUgHiAdTiAdIB9OcQRAIBggGmogG2ohISAXIBpqIBtqISIgGCAaaiAcaiEkQQAhJQNAIAIgIkEBdGovAQAhJiAiQQFqISIgAiAhQQF0ai8BACEnICFBAWohISACICBBAXRqLwEAISggIEEBaiEgIAIgJEEBdGovAQAhKSAkQQFqISQgJyAmayAdbCAmIChrIB5saiApICdrIB9saiEqICggKkGAIGpBDXVqISsgECArOwEAIBBBAmohECAlQQFqIiUgBEgNAAsFIB4gH04gHyAdTnEEQCAYIBpqIBxqISEgFyAaaiAcaiEiIBcgGmogG2ohI0EAISUDQCACICJBAXRqLwEAISYgIkEBaiEiIAIgI0EBdGovAQAhJyAjQQFqISMgAiAgQQF0ai8BACEoICBBAWohICACICFBAXRqLwEAISkgIUEBaiEhICkgJmsgHWwgJyAoayAebGogJiAnayAfbGohKiAoICpBgCBqQQ11aiErIBAgKzsBACAQQQJqIRAgJUEBaiIlIARIDQALBSAfIB5OIB4gHU5xBEAgGCAaaiAcaiEhIBcgGmogHGohIiAXIBlqIBxqISRBACElA0AgAiAiQQF0ai8BACEmICJBAWohIiACICRBAXRqLwEAIScgJEEBaiEkIAIgIEEBdGovAQAhKCAgQQFqISAgAiAhQQF0ai8BACEpICFBAWohISApICZrIB1sICYgJ2sgHmxqICcgKGsgH2xqISogKCAqQYAgakENdWohKyAQICs7AQAgEEECaiEQICVBAWoiJSAESA0ACwVBACElA0AgAiAgQQF0ai8BACEoICBBAWohICAQICg7AQAgEEECaiEQICVBAWoiJSAESA0ACwsLCwsLC0EBITAgLCEuIC0hLyAQIDFrITMLIA1BAkYEQCAQIA8vAQA7AQAgEEECaiEQIA9BAmohDwUgDUEBRgRAIBBB//8DOwEAIBBBAmohEAsgDyAMQQF0aiEPCyAOQQFqIQ4MAAsLCw==';

function decode(b64) {
    if (typeof Buffer !== 'undefined' && typeof Buffer.from === 'function') {
        return new Uint8Array(Buffer.from(b64, 'base64'));
    }
    if (typeof atob === 'function') {
        const bin = atob(b64);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
    }
    throw new Error('No base64 decoder available (need Buffer or atob).');
}

module.exports = decode(BASE64);
