/*************************************************************************
 *  @license
 *
 *  Copyright © 2019, 2026 Glenn Wilton
 *  O2 Creative Limited
 *  www.o2creative.co.nz
 *  support@o2creative.co.nz
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 */

// ============================================================================
// matrix_shaper_int8_simd.wasm.js — AUTO-GENERATED from matrix_shaper_int8_simd.wat
// ============================================================================
//
// Do not edit by hand. Regenerate with:
//   node scripts/build_matrix_shaper_wasm.js
//
// Variant: 8-bit, SIMD, 4 pixels per iteration
// Size: 5646 bytes .wasm
//
// Memory layout:
//   0 .. 1023  input gamma  256 x f32
//   1024 .. 66559  output gamma 65536 x u8
//   66560  matrix 9 x f32
//   66624  pixel data
// ============================================================================

'use strict';

var BASE64 = 'AGFzbQEAAAABBwFgA39/fwADBgUAAAAAAAUDAQACB0EGBm1lbW9yeQIAA3J1bgAACHJ1bl9hX2luAAEJcnVuX2Ffb3V0AAIKcnVuX2FfY29weQADCnJ1bl9hX2ZpbGwABAqqKwW5CAMEfxN7D30gACEEIAEhBUEAKgKAiAQhGkEAKgKEiAQhG0EAKgKIiAQhHEEAKgKMiAQhHUEAKgKQiAQhHkEAKgKUiAQhH0EAKgKYiAQhIEEAKgKciAQhIUEAKgKgiAQhIkMAAAAA/RMhFkMAAIA//RMhF0MA/39H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQtAABBAnQqAgD9EyAELQADQQJ0KgIA/SABIAQtAAZBAnQqAgD9IAIgBC0ACUECdCoCAP0gAyEHIAQtAAFBAnQqAgD9EyAELQAEQQJ0KgIA/SABIAQtAAdBAnQqAgD9IAIgBC0ACkECdCoCAP0gAyEIIAQtAAJBAnQqAgD9EyAELQAFQQJ0KgIA/SABIAQtAAhBAnQqAgD9IAIgBC0AC0ECdCoCAP0gAyEJIARBDGohBCAHIA395gEgCCAO/eYB/eQBIAkgD/3mAf3kASEKIAcgEP3mASAIIBH95gH95AEgCSAS/eYB/eQBIQsgByAT/eYBIAggFP3mAf3kASAJIBX95gH95AEhDCAKIBb96QEgF/3oASAY/eYBIBn95AH9+QEhCiALIBb96QEgF/3oASAY/eYBIBn95AH9+QEhCyAMIBb96QEgF/3oASAY/eYBIBn95AH9+QEhDCAK/RsAIQYgBUGACCAGai0AADoAACAL/RsAIQYgBUGACCAGai0AADoAASAM/RsAIQYgBUGACCAGai0AADoAAiAK/RsBIQYgBUGACCAGai0AADoAAyAL/RsBIQYgBUGACCAGai0AADoABCAM/RsBIQYgBUGACCAGai0AADoABSAK/RsCIQYgBUGACCAGai0AADoABiAL/RsCIQYgBUGACCAGai0AADoAByAM/RsCIQYgBUGACCAGai0AADoACCAK/RsDIQYgBUGACCAGai0AADoACSAL/RsDIQYgBUGACCAGai0AADoACiAM/RsDIQYgBUGACCAGai0AADoACyAFQQxqIQUgA0EEaiEDDAALCwJAA0AgAyACTg0BIAQtAABBAnQqAgAhIyAELQABQQJ0KgIAISQgBC0AAkECdCoCACElIARBA2ohBCAjIBqUICQgG5SSICUgHJSSISYgIyAdlCAkIB6UkiAlIB+UkiEnICMgIJQgJCAhlJIgJSAilJIhKCAmQwAAAACXQwAAgD+WQwD/f0eUQwAAAD+S/AEhBiAFQYAIIAZqLQAAOgAAICdDAAAAAJdDAACAP5ZDAP9/R5RDAAAAP5L8ASEGIAVBgAggBmotAAA6AAEgKEMAAAAAl0MAAIA/lkMA/39HlEMAAAA/kvwBIQYgBUGACCAGai0AADoAAiAFQQNqIQUgA0EBaiEDDAALCwu5CAMEfxN7D30gACEEIAEhBUEAKgKAiAQhGkEAKgKEiAQhG0EAKgKIiAQhHEEAKgKMiAQhHUEAKgKQiAQhHkEAKgKUiAQhH0EAKgKYiAQhIEEAKgKciAQhIUEAKgKgiAQhIkMAAAAA/RMhFkMAAIA//RMhF0MA/39H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQtAABBAnQqAgD9EyAELQAEQQJ0KgIA/SABIAQtAAhBAnQqAgD9IAIgBC0ADEECdCoCAP0gAyEHIAQtAAFBAnQqAgD9EyAELQAFQQJ0KgIA/SABIAQtAAlBAnQqAgD9IAIgBC0ADUECdCoCAP0gAyEIIAQtAAJBAnQqAgD9EyAELQAGQQJ0KgIA/SABIAQtAApBAnQqAgD9IAIgBC0ADkECdCoCAP0gAyEJIARBEGohBCAHIA395gEgCCAO/eYB/eQBIAkgD/3mAf3kASEKIAcgEP3mASAIIBH95gH95AEgCSAS/eYB/eQBIQsgByAT/eYBIAggFP3mAf3kASAJIBX95gH95AEhDCAKIBb96QEgF/3oASAY/eYBIBn95AH9+QEhCiALIBb96QEgF/3oASAY/eYBIBn95AH9+QEhCyAMIBb96QEgF/3oASAY/eYBIBn95AH9+QEhDCAK/RsAIQYgBUGACCAGai0AADoAACAL/RsAIQYgBUGACCAGai0AADoAASAM/RsAIQYgBUGACCAGai0AADoAAiAK/RsBIQYgBUGACCAGai0AADoAAyAL/RsBIQYgBUGACCAGai0AADoABCAM/RsBIQYgBUGACCAGai0AADoABSAK/RsCIQYgBUGACCAGai0AADoABiAL/RsCIQYgBUGACCAGai0AADoAByAM/RsCIQYgBUGACCAGai0AADoACCAK/RsDIQYgBUGACCAGai0AADoACSAL/RsDIQYgBUGACCAGai0AADoACiAM/RsDIQYgBUGACCAGai0AADoACyAFQQxqIQUgA0EEaiEDDAALCwJAA0AgAyACTg0BIAQtAABBAnQqAgAhIyAELQABQQJ0KgIAISQgBC0AAkECdCoCACElIARBBGohBCAjIBqUICQgG5SSICUgHJSSISYgIyAdlCAkIB6UkiAlIB+UkiEnICMgIJQgJCAhlJIgJSAilJIhKCAmQwAAAACXQwAAgD+WQwD/f0eUQwAAAD+S/AEhBiAFQYAIIAZqLQAAOgAAICdDAAAAAJdDAACAP5ZDAP9/R5RDAAAAP5L8ASEGIAVBgAggBmotAAA6AAEgKEMAAAAAl0MAAIA/lkMA/39HlEMAAAA/kvwBIQYgBUGACCAGai0AADoAAiAFQQNqIQUgA0EBaiEDDAALCwvhCAMEfxN7D30gACEEIAEhBUEAKgKAiAQhGkEAKgKEiAQhG0EAKgKIiAQhHEEAKgKMiAQhHUEAKgKQiAQhHkEAKgKUiAQhH0EAKgKYiAQhIEEAKgKciAQhIUEAKgKgiAQhIkMAAAAA/RMhFkMAAIA//RMhF0MA/39H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQtAABBAnQqAgD9EyAELQADQQJ0KgIA/SABIAQtAAZBAnQqAgD9IAIgBC0ACUECdCoCAP0gAyEHIAQtAAFBAnQqAgD9EyAELQAEQQJ0KgIA/SABIAQtAAdBAnQqAgD9IAIgBC0ACkECdCoCAP0gAyEIIAQtAAJBAnQqAgD9EyAELQAFQQJ0KgIA/SABIAQtAAhBAnQqAgD9IAIgBC0AC0ECdCoCAP0gAyEJIAVB/wE6AAMgBUH/AToAByAFQf8BOgALIAVB/wE6AA8gBEEMaiEEIAcgDf3mASAIIA795gH95AEgCSAP/eYB/eQBIQogByAQ/eYBIAggEf3mAf3kASAJIBL95gH95AEhCyAHIBP95gEgCCAU/eYB/eQBIAkgFf3mAf3kASEMIAogFv3pASAX/egBIBj95gEgGf3kAf35ASEKIAsgFv3pASAX/egBIBj95gEgGf3kAf35ASELIAwgFv3pASAX/egBIBj95gEgGf3kAf35ASEMIAr9GwAhBiAFQYAIIAZqLQAAOgAAIAv9GwAhBiAFQYAIIAZqLQAAOgABIAz9GwAhBiAFQYAIIAZqLQAAOgACIAr9GwEhBiAFQYAIIAZqLQAAOgAEIAv9GwEhBiAFQYAIIAZqLQAAOgAFIAz9GwEhBiAFQYAIIAZqLQAAOgAGIAr9GwIhBiAFQYAIIAZqLQAAOgAIIAv9GwIhBiAFQYAIIAZqLQAAOgAJIAz9GwIhBiAFQYAIIAZqLQAAOgAKIAr9GwMhBiAFQYAIIAZqLQAAOgAMIAv9GwMhBiAFQYAIIAZqLQAAOgANIAz9GwMhBiAFQYAIIAZqLQAAOgAOIAVBEGohBSADQQRqIQMMAAsLAkADQCADIAJODQEgBC0AAEECdCoCACEjIAQtAAFBAnQqAgAhJCAELQACQQJ0KgIAISUgBUH/AToAAyAEQQNqIQQgIyAalCAkIBuUkiAlIByUkiEmICMgHZQgJCAelJIgJSAflJIhJyAjICCUICQgIZSSICUgIpSSISggJkMAAAAAl0MAAIA/lkMA/39HlEMAAAA/kvwBIQYgBUGACCAGai0AADoAACAnQwAAAACXQwAAgD+WQwD/f0eUQwAAAD+S/AEhBiAFQYAIIAZqLQAAOgABIChDAAAAAJdDAACAP5ZDAP9/R5RDAAAAP5L8ASEGIAVBgAggBmotAAA6AAIgBUEEaiEFIANBAWohAwwACwsL6wgDBH8Tew99IAAhBCABIQVBACoCgIgEIRpBACoChIgEIRtBACoCiIgEIRxBACoCjIgEIR1BACoCkIgEIR5BACoClIgEIR9BACoCmIgEISBBACoCnIgEISFBACoCoIgEISJDAAAAAP0TIRZDAACAP/0TIRdDAP9/R/0TIRhDAAAAP/0TIRkgGv0TIQ0gG/0TIQ4gHP0TIQ8gHf0TIRAgHv0TIREgH/0TIRIgIP0TIRMgIf0TIRQgIv0TIRUCQANAIANBBGogAkoNASAELQAAQQJ0KgIA/RMgBC0ABEECdCoCAP0gASAELQAIQQJ0KgIA/SACIAQtAAxBAnQqAgD9IAMhByAELQABQQJ0KgIA/RMgBC0ABUECdCoCAP0gASAELQAJQQJ0KgIA/SACIAQtAA1BAnQqAgD9IAMhCCAELQACQQJ0KgIA/RMgBC0ABkECdCoCAP0gASAELQAKQQJ0KgIA/SACIAQtAA5BAnQqAgD9IAMhCSAFIAQtAAM6AAMgBSAELQAHOgAHIAUgBC0ACzoACyAFIAQtAA86AA8gBEEQaiEEIAcgDf3mASAIIA795gH95AEgCSAP/eYB/eQBIQogByAQ/eYBIAggEf3mAf3kASAJIBL95gH95AEhCyAHIBP95gEgCCAU/eYB/eQBIAkgFf3mAf3kASEMIAogFv3pASAX/egBIBj95gEgGf3kAf35ASEKIAsgFv3pASAX/egBIBj95gEgGf3kAf35ASELIAwgFv3pASAX/egBIBj95gEgGf3kAf35ASEMIAr9GwAhBiAFQYAIIAZqLQAAOgAAIAv9GwAhBiAFQYAIIAZqLQAAOgABIAz9GwAhBiAFQYAIIAZqLQAAOgACIAr9GwEhBiAFQYAIIAZqLQAAOgAEIAv9GwEhBiAFQYAIIAZqLQAAOgAFIAz9GwEhBiAFQYAIIAZqLQAAOgAGIAr9GwIhBiAFQYAIIAZqLQAAOgAIIAv9GwIhBiAFQYAIIAZqLQAAOgAJIAz9GwIhBiAFQYAIIAZqLQAAOgAKIAr9GwMhBiAFQYAIIAZqLQAAOgAMIAv9GwMhBiAFQYAIIAZqLQAAOgANIAz9GwMhBiAFQYAIIAZqLQAAOgAOIAVBEGohBSADQQRqIQMMAAsLAkADQCADIAJODQEgBC0AAEECdCoCACEjIAQtAAFBAnQqAgAhJCAELQACQQJ0KgIAISUgBSAELQADOgADIARBBGohBCAjIBqUICQgG5SSICUgHJSSISYgIyAdlCAkIB6UkiAlIB+UkiEnICMgIJQgJCAhlJIgJSAilJIhKCAmQwAAAACXQwAAgD+WQwD/f0eUQwAAAD+S/AEhBiAFQYAIIAZqLQAAOgAAICdDAAAAAJdDAACAP5ZDAP9/R5RDAAAAP5L8ASEGIAVBgAggBmotAAA6AAEgKEMAAAAAl0MAAIA/lkMA/39HlEMAAAA/kvwBIQYgBUGACCAGai0AADoAAiAFQQRqIQUgA0EBaiEDDAALCwvhCAMEfxN7D30gACEEIAEhBUEAKgKAiAQhGkEAKgKEiAQhG0EAKgKIiAQhHEEAKgKMiAQhHUEAKgKQiAQhHkEAKgKUiAQhH0EAKgKYiAQhIEEAKgKciAQhIUEAKgKgiAQhIkMAAAAA/RMhFkMAAIA//RMhF0MA/39H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQtAABBAnQqAgD9EyAELQAEQQJ0KgIA/SABIAQtAAhBAnQqAgD9IAIgBC0ADEECdCoCAP0gAyEHIAQtAAFBAnQqAgD9EyAELQAFQQJ0KgIA/SABIAQtAAlBAnQqAgD9IAIgBC0ADUECdCoCAP0gAyEIIAQtAAJBAnQqAgD9EyAELQAGQQJ0KgIA/SABIAQtAApBAnQqAgD9IAIgBC0ADkECdCoCAP0gAyEJIAVB/wE6AAMgBUH/AToAByAFQf8BOgALIAVB/wE6AA8gBEEQaiEEIAcgDf3mASAIIA795gH95AEgCSAP/eYB/eQBIQogByAQ/eYBIAggEf3mAf3kASAJIBL95gH95AEhCyAHIBP95gEgCCAU/eYB/eQBIAkgFf3mAf3kASEMIAogFv3pASAX/egBIBj95gEgGf3kAf35ASEKIAsgFv3pASAX/egBIBj95gEgGf3kAf35ASELIAwgFv3pASAX/egBIBj95gEgGf3kAf35ASEMIAr9GwAhBiAFQYAIIAZqLQAAOgAAIAv9GwAhBiAFQYAIIAZqLQAAOgABIAz9GwAhBiAFQYAIIAZqLQAAOgACIAr9GwEhBiAFQYAIIAZqLQAAOgAEIAv9GwEhBiAFQYAIIAZqLQAAOgAFIAz9GwEhBiAFQYAIIAZqLQAAOgAGIAr9GwIhBiAFQYAIIAZqLQAAOgAIIAv9GwIhBiAFQYAIIAZqLQAAOgAJIAz9GwIhBiAFQYAIIAZqLQAAOgAKIAr9GwMhBiAFQYAIIAZqLQAAOgAMIAv9GwMhBiAFQYAIIAZqLQAAOgANIAz9GwMhBiAFQYAIIAZqLQAAOgAOIAVBEGohBSADQQRqIQMMAAsLAkADQCADIAJODQEgBC0AAEECdCoCACEjIAQtAAFBAnQqAgAhJCAELQACQQJ0KgIAISUgBUH/AToAAyAEQQRqIQQgIyAalCAkIBuUkiAlIByUkiEmICMgHZQgJCAelJIgJSAflJIhJyAjICCUICQgIZSSICUgIpSSISggJkMAAAAAl0MAAIA/lkMA/39HlEMAAAA/kvwBIQYgBUGACCAGai0AADoAACAnQwAAAACXQwAAgD+WQwD/f0eUQwAAAD+S/AEhBiAFQYAIIAZqLQAAOgABIChDAAAAAJdDAACAP5ZDAP9/R5RDAAAAP5L8ASEGIAVBgAggBmotAAA6AAIgBUEEaiEFIANBAWohAwwACwsL';

function decode(b64) {
    if (typeof Buffer !== 'undefined') return new Uint8Array(Buffer.from(b64, 'base64'));
    if (typeof atob !== 'undefined') {
        var bin = atob(b64), out = new Uint8Array(bin.length);
        for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
    }
    throw new Error('No base64 decoder available (need Buffer or atob).');
}

module.exports = decode(BASE64);
module.exports.LAYOUT = {
    bits:         8,
    gammaInByte:  0,
    gammaOutByte: 1024,
    matrixByte:   66560,
    pixelByte:    66624,
    inEntries:    256,
    outIndexMax:   65535,
    outValueMax:   255,
    outEntryBytes: 1,
    indexRoot:     1
};
