/*************************************************************************
 *  @license
 *
 *  Copyright © 2019, 2026 Glenn Wilton
 *  O2 Creative Limited
 *  www.o2creative.co.nz
 *  support@o2creative.co.nz
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 */

// ============================================================================
// matrix_shaper_int16_simd.wasm.js — AUTO-GENERATED from matrix_shaper_int16_simd.wat
// ============================================================================
//
// Do not edit by hand. Regenerate with:
//   node scripts/build_matrix_shaper_wasm.js
//
// Variant: 16-bit, SIMD, 4 pixels per iteration
// Size: 6076 bytes .wasm
//
// Memory layout:
//   0 .. 262143  input gamma  65536 x f32
//   262144 .. 524287  output gamma 65537 x f32, sqrt-indexed
//   524288  matrix 9 x f32
//   524352  pixel data
// ============================================================================

'use strict';

var BASE64 = 'AGFzbQEAAAABBwFgA39/fwADBgUAAAAAAAUDAQAJB0EGBm1lbW9yeQIAA3J1bgAACHJ1bl9hX2luAAEJcnVuX2Ffb3V0AAIKcnVuX2FfY29weQADCnJ1bl9hX2ZpbGwABArYLgWNCQMEfxN7D30gACEEIAEhBUEAKgKAgCAhGkEAKgKEgCAhG0EAKgKIgCAhHEEAKgKMgCAhHUEAKgKQgCAhHkEAKgKUgCAhH0EAKgKYgCAhIEEAKgKcgCAhIUEAKgKggCAhIkMAAAAA/RMhFkMAAIA//RMhF0OA//9H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQvAQBBAnQqAgD9EyAELwEGQQJ0KgIA/SABIAQvAQxBAnQqAgD9IAIgBC8BEkECdCoCAP0gAyEHIAQvAQJBAnQqAgD9EyAELwEIQQJ0KgIA/SABIAQvAQ5BAnQqAgD9IAIgBC8BFEECdCoCAP0gAyEIIAQvAQRBAnQqAgD9EyAELwEKQQJ0KgIA/SABIAQvARBBAnQqAgD9IAIgBC8BFkECdCoCAP0gAyEJIARBGGohBCAHIA395gEgCCAO/eYB/eQBIAkgD/3mAf3kASEKIAcgEP3mASAIIBH95gH95AEgCSAS/eYB/eQBIQsgByAT/eYBIAggFP3mAf3kASAJIBX95gH95AEhDCAKIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhCiALIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhCyAMIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhDCAK/RsAIQYgBUGAgBAgBkEBdGovAQA7AQAgC/0bACEGIAVBgIAQIAZBAXRqLwEAOwECIAz9GwAhBiAFQYCAECAGQQF0ai8BADsBBCAK/RsBIQYgBUGAgBAgBkEBdGovAQA7AQYgC/0bASEGIAVBgIAQIAZBAXRqLwEAOwEIIAz9GwEhBiAFQYCAECAGQQF0ai8BADsBCiAK/RsCIQYgBUGAgBAgBkEBdGovAQA7AQwgC/0bAiEGIAVBgIAQIAZBAXRqLwEAOwEOIAz9GwIhBiAFQYCAECAGQQF0ai8BADsBECAK/RsDIQYgBUGAgBAgBkEBdGovAQA7ARIgC/0bAyEGIAVBgIAQIAZBAXRqLwEAOwEUIAz9GwMhBiAFQYCAECAGQQF0ai8BADsBFiAFQRhqIQUgA0EEaiEDDAALCwJAA0AgAyACTg0BIAQvAQBBAnQqAgAhIyAELwECQQJ0KgIAISQgBC8BBEECdCoCACElIARBBmohBCAjIBqUICQgG5SSICUgHJSSISYgIyAdlCAkIB6UkiAlIB+UkiEnICMgIJQgJCAhlJIgJSAilJIhKCAmQwAAAACXQwAAgD+WkZFDgP//R5RDAAAAP5L8ASEGIAVBgIAQIAZBAXRqLwEAOwEAICdDAAAAAJdDAACAP5aRkUOA//9HlEMAAAA/kvwBIQYgBUGAgBAgBkEBdGovAQA7AQIgKEMAAAAAl0MAAIA/lpGRQ4D//0eUQwAAAD+S/AEhBiAFQYCAECAGQQF0ai8BADsBBCAFQQZqIQUgA0EBaiEDDAALCwuNCQMEfxN7D30gACEEIAEhBUEAKgKAgCAhGkEAKgKEgCAhG0EAKgKIgCAhHEEAKgKMgCAhHUEAKgKQgCAhHkEAKgKUgCAhH0EAKgKYgCAhIEEAKgKcgCAhIUEAKgKggCAhIkMAAAAA/RMhFkMAAIA//RMhF0OA//9H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQvAQBBAnQqAgD9EyAELwEIQQJ0KgIA/SABIAQvARBBAnQqAgD9IAIgBC8BGEECdCoCAP0gAyEHIAQvAQJBAnQqAgD9EyAELwEKQQJ0KgIA/SABIAQvARJBAnQqAgD9IAIgBC8BGkECdCoCAP0gAyEIIAQvAQRBAnQqAgD9EyAELwEMQQJ0KgIA/SABIAQvARRBAnQqAgD9IAIgBC8BHEECdCoCAP0gAyEJIARBIGohBCAHIA395gEgCCAO/eYB/eQBIAkgD/3mAf3kASEKIAcgEP3mASAIIBH95gH95AEgCSAS/eYB/eQBIQsgByAT/eYBIAggFP3mAf3kASAJIBX95gH95AEhDCAKIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhCiALIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhCyAMIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhDCAK/RsAIQYgBUGAgBAgBkEBdGovAQA7AQAgC/0bACEGIAVBgIAQIAZBAXRqLwEAOwECIAz9GwAhBiAFQYCAECAGQQF0ai8BADsBBCAK/RsBIQYgBUGAgBAgBkEBdGovAQA7AQYgC/0bASEGIAVBgIAQIAZBAXRqLwEAOwEIIAz9GwEhBiAFQYCAECAGQQF0ai8BADsBCiAK/RsCIQYgBUGAgBAgBkEBdGovAQA7AQwgC/0bAiEGIAVBgIAQIAZBAXRqLwEAOwEOIAz9GwIhBiAFQYCAECAGQQF0ai8BADsBECAK/RsDIQYgBUGAgBAgBkEBdGovAQA7ARIgC/0bAyEGIAVBgIAQIAZBAXRqLwEAOwEUIAz9GwMhBiAFQYCAECAGQQF0ai8BADsBFiAFQRhqIQUgA0EEaiEDDAALCwJAA0AgAyACTg0BIAQvAQBBAnQqAgAhIyAELwECQQJ0KgIAISQgBC8BBEECdCoCACElIARBCGohBCAjIBqUICQgG5SSICUgHJSSISYgIyAdlCAkIB6UkiAlIB+UkiEnICMgIJQgJCAhlJIgJSAilJIhKCAmQwAAAACXQwAAgD+WkZFDgP//R5RDAAAAP5L8ASEGIAVBgIAQIAZBAXRqLwEAOwEAICdDAAAAAJdDAACAP5aRkUOA//9HlEMAAAA/kvwBIQYgBUGAgBAgBkEBdGovAQA7AQIgKEMAAAAAl0MAAIA/lpGRQ4D//0eUQwAAAD+S/AEhBiAFQYCAECAGQQF0ai8BADsBBCAFQQZqIQUgA0EBaiEDDAALCwu6CQMEfxN7D30gACEEIAEhBUEAKgKAgCAhGkEAKgKEgCAhG0EAKgKIgCAhHEEAKgKMgCAhHUEAKgKQgCAhHkEAKgKUgCAhH0EAKgKYgCAhIEEAKgKcgCAhIUEAKgKggCAhIkMAAAAA/RMhFkMAAIA//RMhF0OA//9H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQvAQBBAnQqAgD9EyAELwEGQQJ0KgIA/SABIAQvAQxBAnQqAgD9IAIgBC8BEkECdCoCAP0gAyEHIAQvAQJBAnQqAgD9EyAELwEIQQJ0KgIA/SABIAQvAQ5BAnQqAgD9IAIgBC8BFEECdCoCAP0gAyEIIAQvAQRBAnQqAgD9EyAELwEKQQJ0KgIA/SABIAQvARBBAnQqAgD9IAIgBC8BFkECdCoCAP0gAyEJIAVB//8DOwEGIAVB//8DOwEOIAVB//8DOwEWIAVB//8DOwEeIARBGGohBCAHIA395gEgCCAO/eYB/eQBIAkgD/3mAf3kASEKIAcgEP3mASAIIBH95gH95AEgCSAS/eYB/eQBIQsgByAT/eYBIAggFP3mAf3kASAJIBX95gH95AEhDCAKIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhCiALIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhCyAMIBb96QEgF/3oAf3jAf3jASAY/eYBIBn95AH9+QEhDCAK/RsAIQYgBUGAgBAgBkEBdGovAQA7AQAgC/0bACEGIAVBgIAQIAZBAXRqLwEAOwECIAz9GwAhBiAFQYCAECAGQQF0ai8BADsBBCAK/RsBIQYgBUGAgBAgBkEBdGovAQA7AQggC/0bASEGIAVBgIAQIAZBAXRqLwEAOwEKIAz9GwEhBiAFQYCAECAGQQF0ai8BADsBDCAK/RsCIQYgBUGAgBAgBkEBdGovAQA7ARAgC/0bAiEGIAVBgIAQIAZBAXRqLwEAOwESIAz9GwIhBiAFQYCAECAGQQF0ai8BADsBFCAK/RsDIQYgBUGAgBAgBkEBdGovAQA7ARggC/0bAyEGIAVBgIAQIAZBAXRqLwEAOwEaIAz9GwMhBiAFQYCAECAGQQF0ai8BADsBHCAFQSBqIQUgA0EEaiEDDAALCwJAA0AgAyACTg0BIAQvAQBBAnQqAgAhIyAELwECQQJ0KgIAISQgBC8BBEECdCoCACElIAVB//8DOwEGIARBBmohBCAjIBqUICQgG5SSICUgHJSSISYgIyAdlCAkIB6UkiAlIB+UkiEnICMgIJQgJCAhlJIgJSAilJIhKCAmQwAAAACXQwAAgD+WkZFDgP//R5RDAAAAP5L8ASEGIAVBgIAQIAZBAXRqLwEAOwEAICdDAAAAAJdDAACAP5aRkUOA//9HlEMAAAA/kvwBIQYgBUGAgBAgBkEBdGovAQA7AQIgKEMAAAAAl0MAAIA/lpGRQ4D//0eUQwAAAD+S/AEhBiAFQYCAECAGQQF0ai8BADsBBCAFQQhqIQUgA0EBaiEDDAALCwu/CQMEfxN7D30gACEEIAEhBUEAKgKAgCAhGkEAKgKEgCAhG0EAKgKIgCAhHEEAKgKMgCAhHUEAKgKQgCAhHkEAKgKUgCAhH0EAKgKYgCAhIEEAKgKcgCAhIUEAKgKggCAhIkMAAAAA/RMhFkMAAIA//RMhF0OA//9H/RMhGEMAAAA//RMhGSAa/RMhDSAb/RMhDiAc/RMhDyAd/RMhECAe/RMhESAf/RMhEiAg/RMhEyAh/RMhFCAi/RMhFQJAA0AgA0EEaiACSg0BIAQvAQBBAnQqAgD9EyAELwEIQQJ0KgIA/SABIAQvARBBAnQqAgD9IAIgBC8BGEECdCoCAP0gAyEHIAQvAQJBAnQqAgD9EyAELwEKQQJ0KgIA/SABIAQvARJBAnQqAgD9IAIgBC8BGkECdCoCAP0gAyEIIAQvAQRBAnQqAgD9EyAELwEMQQJ0KgIA/SABIAQvARRBAnQqAgD9IAIgBC8BHEECdCoCAP0gAyEJIAUgBC8BBjsBBiAFIAQvAQ47AQ4gBSAELwEWOwEWIAUgBC8BHjsBHiAEQSBqIQQgByAN/eYBIAggDv3mAf3kASAJIA/95gH95AEhCiAHIBD95gEgCCAR/eYB/eQBIAkgEv3mAf3kASELIAcgE/3mASAIIBT95gH95AEgCSAV/eYB/eQBIQwgCiAW/ekBIBf96AH94wH94wEgGP3mASAZ/eQB/fkBIQogCyAW/ekBIBf96AH94wH94wEgGP3mASAZ/eQB/fkBIQsgDCAW/ekBIBf96AH94wH94wEgGP3mASAZ/eQB/fkBIQwgCv0bACEGIAVBgIAQIAZBAXRqLwEAOwEAIAv9GwAhBiAFQYCAECAGQQF0ai8BADsBAiAM/RsAIQYgBUGAgBAgBkEBdGovAQA7AQQgCv0bASEGIAVBgIAQIAZBAXRqLwEAOwEIIAv9GwEhBiAFQYCAECAGQQF0ai8BADsBCiAM/RsBIQYgBUGAgBAgBkEBdGovAQA7AQwgCv0bAiEGIAVBgIAQIAZBAXRqLwEAOwEQIAv9GwIhBiAFQYCAECAGQQF0ai8BADsBEiAM/RsCIQYgBUGAgBAgBkEBdGovAQA7ARQgCv0bAyEGIAVBgIAQIAZBAXRqLwEAOwEYIAv9GwMhBiAFQYCAECAGQQF0ai8BADsBGiAM/RsDIQYgBUGAgBAgBkEBdGovAQA7ARwgBUEgaiEFIANBBGohAwwACwsCQANAIAMgAk4NASAELwEAQQJ0KgIAISMgBC8BAkECdCoCACEkIAQvAQRBAnQqAgAhJSAFIAQvAQY7AQYgBEEIaiEEICMgGpQgJCAblJIgJSAclJIhJiAjIB2UICQgHpSSICUgH5SSIScgIyAglCAkICGUkiAlICKUkiEoICZDAAAAAJdDAACAP5aRkUOA//9HlEMAAAA/kvwBIQYgBUGAgBAgBkEBdGovAQA7AQAgJ0MAAAAAl0MAAIA/lpGRQ4D//0eUQwAAAD+S/AEhBiAFQYCAECAGQQF0ai8BADsBAiAoQwAAAACXQwAAgD+WkZFDgP//R5RDAAAAP5L8ASEGIAVBgIAQIAZBAXRqLwEAOwEEIAVBCGohBSADQQFqIQMMAAsLC7oJAwR/E3sPfSAAIQQgASEFQQAqAoCAICEaQQAqAoSAICEbQQAqAoiAICEcQQAqAoyAICEdQQAqApCAICEeQQAqApSAICEfQQAqApiAICEgQQAqApyAICEhQQAqAqCAICEiQwAAAAD9EyEWQwAAgD/9EyEXQ4D//0f9EyEYQwAAAD/9EyEZIBr9EyENIBv9EyEOIBz9EyEPIB39EyEQIB79EyERIB/9EyESICD9EyETICH9EyEUICL9EyEVAkADQCADQQRqIAJKDQEgBC8BAEECdCoCAP0TIAQvAQhBAnQqAgD9IAEgBC8BEEECdCoCAP0gAiAELwEYQQJ0KgIA/SADIQcgBC8BAkECdCoCAP0TIAQvAQpBAnQqAgD9IAEgBC8BEkECdCoCAP0gAiAELwEaQQJ0KgIA/SADIQggBC8BBEECdCoCAP0TIAQvAQxBAnQqAgD9IAEgBC8BFEECdCoCAP0gAiAELwEcQQJ0KgIA/SADIQkgBUH//wM7AQYgBUH//wM7AQ4gBUH//wM7ARYgBUH//wM7AR4gBEEgaiEEIAcgDf3mASAIIA795gH95AEgCSAP/eYB/eQBIQogByAQ/eYBIAggEf3mAf3kASAJIBL95gH95AEhCyAHIBP95gEgCCAU/eYB/eQBIAkgFf3mAf3kASEMIAogFv3pASAX/egB/eMB/eMBIBj95gEgGf3kAf35ASEKIAsgFv3pASAX/egB/eMB/eMBIBj95gEgGf3kAf35ASELIAwgFv3pASAX/egB/eMB/eMBIBj95gEgGf3kAf35ASEMIAr9GwAhBiAFQYCAECAGQQF0ai8BADsBACAL/RsAIQYgBUGAgBAgBkEBdGovAQA7AQIgDP0bACEGIAVBgIAQIAZBAXRqLwEAOwEEIAr9GwEhBiAFQYCAECAGQQF0ai8BADsBCCAL/RsBIQYgBUGAgBAgBkEBdGovAQA7AQogDP0bASEGIAVBgIAQIAZBAXRqLwEAOwEMIAr9GwIhBiAFQYCAECAGQQF0ai8BADsBECAL/RsCIQYgBUGAgBAgBkEBdGovAQA7ARIgDP0bAiEGIAVBgIAQIAZBAXRqLwEAOwEUIAr9GwMhBiAFQYCAECAGQQF0ai8BADsBGCAL/RsDIQYgBUGAgBAgBkEBdGovAQA7ARogDP0bAyEGIAVBgIAQIAZBAXRqLwEAOwEcIAVBIGohBSADQQRqIQMMAAsLAkADQCADIAJODQEgBC8BAEECdCoCACEjIAQvAQJBAnQqAgAhJCAELwEEQQJ0KgIAISUgBUH//wM7AQYgBEEIaiEEICMgGpQgJCAblJIgJSAclJIhJiAjIB2UICQgHpSSICUgH5SSIScgIyAglCAkICGUkiAlICKUkiEoICZDAAAAAJdDAACAP5aRkUOA//9HlEMAAAA/kvwBIQYgBUGAgBAgBkEBdGovAQA7AQAgJ0MAAAAAl0MAAIA/lpGRQ4D//0eUQwAAAD+S/AEhBiAFQYCAECAGQQF0ai8BADsBAiAoQwAAAACXQwAAgD+WkZFDgP//R5RDAAAAP5L8ASEGIAVBgIAQIAZBAXRqLwEAOwEEIAVBCGohBSADQQFqIQMMAAsLCw==';

function decode(b64) {
    if (typeof Buffer !== 'undefined') return new Uint8Array(Buffer.from(b64, 'base64'));
    if (typeof atob !== 'undefined') {
        var bin = atob(b64), out = new Uint8Array(bin.length);
        for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
    }
    throw new Error('No base64 decoder available (need Buffer or atob).');
}

module.exports = decode(BASE64);
module.exports.LAYOUT = {
    bits:         16,
    gammaInByte:  0,
    gammaOutByte: 262144,
    matrixByte:   524288,
    pixelByte:    524352,
    inEntries:    65536,
    outIndexMax:   131071,
    outValueMax:   65535,
    outEntryBytes: 2,
    indexRoot:     4
};
