/**
 * DeviceLink ('link'-class) profile support.
 *
 * Two families of fixtures, both with self-validating math:
 *
 *  testbed/profiles/lcms_testbed/ — generated by the LittleCMS testbed:
 *    linlcms2.icc    curves-only mAB (B-curves, parametric gamma 3.0)
 *                    → out = in^3 exactly
 *    limitlcms2.icc  CMYK→CMYK ink-limit link (150%): K preserved, CMY
 *                    scaled into the remaining budget — lcms's algorithm
 *                    reproduced bit-for-bit at the grid points
 *
 *  testbed/profiles/devicelink/ — Serendipity Software sample links
 *  (https://www.serendipity-software.com.au/support/download/devicelink-profiles):
 *    null-cmyk-to-cmyk.icc   identity CMYK→CMYK (mft2)
 *    null-rgb-to-rgb.icc     identity RGB→RGB (mft2)
 *    simple-cmyk-to-rgb.icc  asymmetric 4→3 link
 *    simple-rgb-to-cmyk.icc  asymmetric 3→4 link (K-only grey axis)
 */

const path = require('path');
const { Transform, Profile, eIntent } = require('../src/main.js');

function loadLink(rel){
    const p = new Profile();
    p.loadFile(path.join(__dirname, '..', rel));
    return p;
}

function makeTransform(profile, opts){
    const t = new Transform(Object.assign({ dataFormat: 'device', buildLut: false }, opts));
    t.create(profile);
    return t;
}

describe('DeviceLink — profile decode', () => {

    test('link class loads with input/output channels resolved from header', () => {
        const p = loadLink('testbed/profiles/lcms_testbed/limitlcms2.icc');
        expect(p.loaded).toBe(true);
        expect(p.header.pClass).toBe('link');
        expect(p.deviceLinkInputChannels).toBe(4);
        expect(p.outputChannels).toBe(4);
        expect(p.mediaWhitePoint).toBeFalsy();       // no wtpt tag — must not crash
    });

    test('asymmetric links resolve input and output sides separately', () => {
        const cmyk2rgb = loadLink('testbed/profiles/devicelink/simple-cmyk-to-rgb.icc');
        expect(cmyk2rgb.deviceLinkInputChannels).toBe(4);
        expect(cmyk2rgb.outputChannels).toBe(3);

        const rgb2cmyk = loadLink('testbed/profiles/devicelink/simple-rgb-to-cmyk.icc');
        expect(rgb2cmyk.deviceLinkInputChannels).toBe(3);
        expect(rgb2cmyk.outputChannels).toBe(4);
    });

    test('curves-only mAB (no CLUT) decodes without crashing', () => {
        const p = loadLink('testbed/profiles/lcms_testbed/linlcms2.icc');
        expect(p.loaded).toBe(true);
        expect(p.A2B[0].CLUT).toBe(false);
        expect(p.A2B[0].bCurves.length).toBe(4);
    });
});

describe('DeviceLink — lcms testbed links (known math)', () => {

    test('linearization link applies gamma 3.0 exactly', () => {
        const t = makeTransform(loadLink('testbed/profiles/lcms_testbed/linlcms2.icc'));
        expect(t.inputChannels).toBe(4);
        expect(t.outputChannels).toBe(4);

        const mid = t.transform([0.5, 0.5, 0.5, 0.5]);
        for(const v of mid) expect(v).toBeCloseTo(Math.pow(0.5, 3), 10);

        expect(t.transform([0, 0, 0, 0])).toEqual([0, 0, 0, 0]);
        for(const v of t.transform([1, 1, 1, 1])) expect(v).toBeCloseTo(1, 10);
    });

    test('ink-limit link reproduces the lcms 150% limiting algorithm', () => {
        const t = makeTransform(loadLink('testbed/profiles/lcms_testbed/limitlcms2.icc'));

        // 400% in → K kept at 1.0, CMY scaled to the remaining 50%: 1/6 each
        const full = t.transform([1, 1, 1, 1]);
        expect(full[3]).toBeCloseTo(1, 3);
        for(let c = 0; c < 3; c++) expect(full[c]).toBeCloseTo(1 / 6, 3);

        // 200% in → K 0.5, CMY scaled to 1/3 each (total exactly 150%)
        const half = t.transform([0.5, 0.5, 0.5, 0.5]);
        expect(half[3]).toBeCloseTo(0.5, 3);
        for(let c = 0; c < 3; c++) expect(half[c]).toBeCloseTo(1 / 3, 3);

        // Under the limit → untouched
        const cOnly = t.transform([1, 0, 0, 0]);
        expect(cOnly[0]).toBeCloseTo(1, 3);
        expect(cOnly[1] + cOnly[2] + cOnly[3]).toBeCloseTo(0, 3);
    });
});

describe('DeviceLink — Serendipity sample links', () => {

    test('null CMYK→CMYK is an identity transform', () => {
        const t = makeTransform(loadLink('testbed/profiles/devicelink/null-cmyk-to-cmyk.icc'));
        for(const probe of [[0, 0, 0, 0], [0.5, 0.5, 0.5, 0.5], [1, 1, 1, 1], [0.2, 0.4, 0.6, 0.8]]){
            const out = t.transform(probe);
            for(let c = 0; c < 4; c++) expect(out[c]).toBeCloseTo(probe[c], 3);
        }
    });

    test('null RGB→RGB is an identity transform', () => {
        const t = makeTransform(loadLink('testbed/profiles/devicelink/null-rgb-to-rgb.icc'));
        for(const probe of [[0, 0, 0], [0.5, 0.5, 0.5], [1, 1, 1], [0.1, 0.5, 0.9]]){
            const out = t.transform(probe);
            for(let c = 0; c < 3; c++) expect(out[c]).toBeCloseTo(probe[c], 3);
        }
    });

    test('simple CMYK→RGB maps ink extremes to white/black', () => {
        const t = makeTransform(loadLink('testbed/profiles/devicelink/simple-cmyk-to-rgb.icc'));
        expect(t.inputChannels).toBe(4);
        expect(t.outputChannels).toBe(3);
        for(const v of t.transform([0, 0, 0, 0])) expect(v).toBeCloseTo(1, 3);   // no ink → white
        for(const v of t.transform([1, 1, 1, 1])) expect(v).toBeCloseTo(0, 3);   // full ink → black
    });

    test('simple RGB→CMYK puts the grey axis on K only', () => {
        const t = makeTransform(loadLink('testbed/profiles/devicelink/simple-rgb-to-cmyk.icc'));
        expect(t.inputChannels).toBe(3);
        expect(t.outputChannels).toBe(4);

        const black = t.transform([0, 0, 0]);
        expect(black[3]).toBeCloseTo(1, 3);
        expect(black[0] + black[1] + black[2]).toBeCloseTo(0, 3);

        const white = t.transform([1, 1, 1]);
        for(const v of white) expect(v).toBeCloseTo(0, 3);

        const grey = t.transform([0.5, 0.5, 0.5]);
        expect(grey[3]).toBeCloseTo(0.5, 2);
    });
});

describe('DeviceLink — Transform integration', () => {

    test('buildLut bakes and transformArray runs the image path', () => {
        const p = loadLink('testbed/profiles/lcms_testbed/limitlcms2.icc');
        const t = new Transform({ dataFormat: 'int8', buildLut: true, lutMode: 'int' });
        t.create(p);
        expect(t.hasLut()).toBe(true);

        // 400% ink pixel + clean cyan pixel
        const out = t.transformArray(new Uint8ClampedArray([255, 255, 255, 255, 255, 0, 0, 0]), false, false);
        expect(out.length).toBe(8);
        expect(out[3]).toBe(255);                                  // K preserved
        for(let c = 0; c < 3; c++) expect(Math.abs(out[c] - 255 / 6)).toBeLessThanOrEqual(2);
        expect(out[4]).toBe(255);                                  // cyan untouched
        expect(out[5] + out[6] + out[7]).toBeLessThanOrEqual(2);
    });

    test('identity detection never collapses a DeviceLink', () => {
        const p = loadLink('testbed/profiles/devicelink/null-cmyk-to-cmyk.icc');
        const t = new Transform({ dataFormat: 'device', buildLut: false, detectIdentity: true });
        t.create(p);
        expect(t.isIdentity).toBe(false);
        expect(t.pipeline.length).toBeGreaterThan(0);
    });

    test('linking a DeviceLink with further profiles throws', () => {
        const p = loadLink('testbed/profiles/lcms_testbed/limitlcms2.icc');
        const t = new Transform({ dataFormat: 'device', buildLut: false });
        expect(() => t.create(p, '*srgb', eIntent.relative))
            .toThrow(/complete device-to-device transform/);
    });
});
